---
title: "Untitled"
output: html_document
date: "2024-05-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(data.table)
library(sets)
library(stringr)
library(tidyr)
library(stargazer)
```


```{r}
usda_data = read.csv("../Data/usda_data.csv")
head(usda_data, 10)
neighbor_county_updated = read.csv("../Data/neighbor_county_updated.csv")
head(neighbor_county_updated, 10)

values_to_filter <- c(2527, 1470, 2128, 973, 2431, 3022, 867, 767, 2039, 85, 2243, 1, 298, 2827, 1642, 1299, 1884, 674, 366, 1387, 571, 220, 161, 2206, 2364, 1094, 1215, 2966, 1821, 1585, 2926, 526, 1787, 2782, 1985, 2317, 69, 3095, 1176, 2812, 1159, 1736, 1200, 1765, 285, 1754, 294, 2311)

state_subset <- usda_data[usda_data$X %in% values_to_filter, ]
state_subset$state <- tolower(state_subset$state)
state_subset$state <- gsub("_", " ", state_subset$state)
```


```{r}

usda_w_pop_and_area = read.csv("../Data/usda_w_pop_and_area.csv")
head(usda_w_pop_and_area, 10)

neighbor_county_filtered <- neighbor_county_updated[!(neighbor_county_updated$state == neighbor_county_updated$neighboring_state & neighbor_county_updated$county == neighbor_county_updated$neighboring_county), ]

usda_w_pop_and_area_simplified = dplyr::select(usda_w_pop_and_area, "region", "subregion", "Population..2020.census.", "Area..mi.2.")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]
neighbor_county_updated <- subset(neighbor_county_updated, county != "buenavistacity")
neighbor_county_updated <- subset(neighbor_county_updated, neighboring_county != "buenavistacity")

neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)
neighboring_count_summed <- neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`))
neighboring_count_summed

```

```{r}
usda_w_pop_and_area_simplified = dplyr::select(usda_w_pop_and_area, "region", 
                                        "subregion", 
                                        "Population..2020.census.", 
                                        "Area..mi.2.",
                                        "cattle.farms",
                                        "cattle.count",
                                        "hog.farm",
                                        "hog.count",
                                        "sheep.farm",
                                        "sheep.count",
                                        "broiler.farm",
                                        "broiler.count",
                                        "layer.farm",
                                        "layer.count")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]
usda_w_pop_and_area_simplified[is.na(usda_w_pop_and_area_simplified)] <- 0

neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

neighboring_count$sheep.count <- as.integer(gsub(-47, 0, neighboring_count$sheep.count))
neighboring_count$hog.count <- as.integer(gsub(-47, 0, neighboring_count$hog.count))
neighboring_count$cattle.count <- as.integer(gsub(-47, 0, neighboring_count$cattle.count))
neighboring_count$layer.count <- as.integer(gsub(-47, 0, neighboring_count$layer.count))
neighboring_count$broiler.count <- as.integer(gsub(-47, 0, neighboring_count$broiler.count))

neighboring_count$sheep.count[is.na(neighboring_count$sheep.count)] <- 0
neighboring_count$hog.count[is.na(neighboring_count$hog.count)] <- 0
neighboring_count$cattle.count[is.na(neighboring_count$cattle.count)] <- 0
neighboring_count$layer.count[is.na(neighboring_count$layer.count)] <- 0
neighboring_count$broiler.count[is.na(neighboring_count$broiler.count)] <- 0

neighboring_count$sheep.farm[is.na(neighboring_count$sheep.farm)] <- 0
neighboring_count$hog.farm[is.na(neighboring_count$hog.farm)] <- 0
neighboring_count$cattle.farms[is.na(neighboring_count$cattle.farms)] <- 0
neighboring_count$layer.farm[is.na(neighboring_count$layer.farm)] <- 0
neighboring_count$broiler.farm[is.na(neighboring_count$broiler.farm)] <- 0
values_to_filter <- c(2029, 10868, 11374)

neighboring_count <- neighboring_count[-values_to_filter, ]

```


```{r}
sheep_neighboring_count = neighboring_count

sheep_neighboring_count_summed <- sheep_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )


linear_model_data_sheep = merge(
  sheep_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_sheep = merge(
  linear_model_data_sheep,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_sheep$surrounding_population_density = linear_model_data_sheep$pop_summed / linear_model_data_sheep$area_summed
linear_model_data_sheep$population_density = linear_model_data_sheep$Population..2020.census. / linear_model_data_sheep$Area..mi.2.
linear_model_data_sheep$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_sheep$county.x)
linear_model_data_sheep$animal_density <- linear_model_data_sheep$sheep.count.x / linear_model_data_sheep$Area..mi.2.
linear_model_data_sheep$surrounding_animal_density <- linear_model_data_sheep$sheep.count.x / linear_model_data_sheep$Area..mi.2.
linear_model_data_sheep$surrounding_animal_density <- linear_model_data_sheep$sheep_count_summed / linear_model_data_sheep$area_summed


write.csv(linear_model_data_sheep, "../Data/linear_model_data_sheep.csv", row.names = FALSE)


head(linear_model_data_sheep)
```

```{r}
cattle_neighboring_count = neighboring_count

cattle_neighboring_count_summed <- cattle_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_cattle = merge(
  cattle_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_cattle = merge(
  linear_model_data_cattle,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_cattle$surrounding_population_density = linear_model_data_cattle$pop_summed / linear_model_data_cattle$area_summed
linear_model_data_cattle$population_density = linear_model_data_cattle$Population..2020.census. / linear_model_data_cattle$Area..mi.2.
linear_model_data_cattle$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_cattle$county.x)
linear_model_data_cattle$animal_density <- linear_model_data_cattle$cattle.count.x / linear_model_data_cattle$Area..mi.2.
linear_model_data_cattle$surrounding_animal_density <- linear_model_data_cattle$cattle_count_summed / linear_model_data_cattle$area_summed


write.csv(linear_model_data_cattle, "../Data/linear_model_data_cattle.csv", row.names = FALSE)


head(linear_model_data_cattle, 10)
```

```{r}
broiler_neighboring_count = neighboring_count

broiler_neighboring_count_summed <- broiler_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_broiler = merge(
  broiler_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_broiler$surrounding_population_density = linear_model_data_broiler$pop_summed / linear_model_data_broiler$area_summed
linear_model_data_broiler$population_density = linear_model_data_broiler$Population..2020.census. / linear_model_data_broiler$Area..mi.2.
linear_model_data_broiler$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_broiler$county.x)
linear_model_data_broiler$animal_density <- linear_model_data_broiler$cattle.count.x / linear_model_data_broiler$Area..mi.2.
linear_model_data_broiler$surrounding_animal_density <- linear_model_data_broiler$broiler_count_summed / linear_model_data_broiler$area_summed


write.csv(linear_model_data_broiler, "../Data/linear_model_data_broiler.csv", row.names = FALSE)



head(linear_model_data_broiler, 10)
```

```{r}
layer_neighboring_count = neighboring_count

layer_neighboring_count_summed <- layer_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_layer = merge(
  layer_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_layer = merge(
  linear_model_data_layer,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_layer$surrounding_population_density = linear_model_data_layer$pop_summed / linear_model_data_layer$area_summed
linear_model_data_layer$population_density = linear_model_data_layer$Population..2020.census. / linear_model_data_layer$Area..mi.2.
linear_model_data_layer$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_layer$county.x)
linear_model_data_layer$animal_density <- linear_model_data_layer$layer.count.x / linear_model_data_layer$Area..mi.2.
linear_model_data_layer$surrounding_animal_density <- linear_model_data_layer$layer_count_summed / linear_model_data_layer$area_summed


write.csv(linear_model_data_layer, "../Data/linear_model_data_layer.csv", row.names = FALSE)

head(linear_model_data_layer, 10)
```

```{r}
hog_neighboring_count = neighboring_count

hog_neighboring_count_summed <- hog_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_hog = merge(
  hog_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_hog = merge(
  linear_model_data_hog,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_hog$surrounding_population_density = linear_model_data_hog$pop_summed / linear_model_data_hog$area_summed
linear_model_data_hog$population_density = linear_model_data_hog$Population..2020.census. / linear_model_data_hog$Area..mi.2.
linear_model_data_hog$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_hog$county.x)
linear_model_data_hog$animal_density <- linear_model_data_hog$hog.count.x / linear_model_data_hog$Area..mi.2.
linear_model_data_hog$surrounding_animal_density <- linear_model_data_hog$hog_count_summed / linear_model_data_hog$area_summed


head(linear_model_data_hog, 10)

write.csv(linear_model_data_hog, "../Data/linear_model_data_hog.csv", row.names = FALSE)

```

