---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ggplot2)
library(dplyr)
library(data.table)
library(sets)
library(stringr)
library(tidyr)
library(stargazer)
```

```{r}
usda_data = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/usda_data.csv")
head(usda_data, 10)
```

```{r}
# Specify the values to filter
values_to_filter <- c(2527, 1470, 2128, 973, 2431, 3022, 867, 767, 2039, 85, 2243, 1, 298, 2827, 1642, 1299, 1884, 674, 366, 1387, 571, 220, 161, 2206, 2364, 1094, 1215, 2966, 1821, 1585, 2926, 526, 1787, 2782, 1985, 2317, 69, 3095, 1176, 2812, 1159, 1736, 1200, 1765, 285, 1754, 294, 2311)

state_subset <- usda_data[usda_data$X %in% values_to_filter, ]
state_subset$state <- tolower(state_subset$state)
state_subset$state <- gsub("_", " ", state_subset$state)

county_subset <- usda_data[!(usda_data$X %in% values_to_filter), ]
county_subset$state <- tolower(county_subset$state)
county_subset$county <- tolower(county_subset$county)
county_subset$state <- gsub("_", " ", county_subset$state)
county_subset$county <- gsub("_", "", county_subset$county)
county_subset$county <- gsub("\\.", "", county_subset$county)
county_subset$county <- gsub(" ", "", county_subset$county)
county_subset$county <- gsub("'", "", county_subset$county)

write.csv(county_subset, "C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/county_subset.csv", row.names = FALSE)

```

```{r, echo=TRUE, results='markup'}
states <- map_data("state")
states$subregion[is.na(states$subregion)] <- "none"

state_subset_map <- merge(states, state_subset, sort = FALSE, by.x = 'region', by.y = 'state')
state_subset_map <- state_subset_map[order(state_subset_map$order), ]

count_variables <- c("hog.count", "cattle.count", "broiler.count", "layer.count", "sheep.count")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable) 
  p <- ggplot(state_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get(variable))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count")  
  print(p)
}
```
```{r}
state_subset
```

```{r, echo=TRUE, results='markup'}
states <- map_data("state")
states$subregion[is.na(states$subregion)] <- "none"

state_subset_map <- merge(states, state_subset, sort = FALSE, by.x = 'region', by.y = 'state')
state_subset_map <- state_subset_map[order(state_subset_map$order), ]

count_variables <- c("hog.farm", "cattle.farms", "broiler.farm", "layer.farm", "sheep.farm")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable)  
  p <- ggplot(state_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get(variable))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count") 
  print(p)
}
```

```{r}
counties <- map_data("county")
counties$subregion[is.na(counties$subregion)] <- "none"
counties$subregion <- gsub(" ", "", counties$subregion)

county_subset_map <- merge(counties, county_subset, sort = FALSE, by.x = c('region', 'subregion'), by.y = c('state', 'county'))
county_subset_map <- county_subset_map[order(county_subset_map$order), ]

count_variables <- c("hog.farm", "cattle.farms", "broiler.farm", "layer.farm", "sheep.farm")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable) 
  p <- ggplot(county_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = ifelse(get(variable) == -47, "red", get(variable)))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count")  
  print(p)
}
```


```{r}
/
```

```{r}
i
```

```{r}

state_missing = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/state_missing.csv")
head(state_missing, 10)

```

```{r}
state_names = unique(state_missing$state)


for (i in state_names) {
  if (state_missing[state_missing$state == i, ]$hog.count_state != state_missing[state_missing$state == i, ]$hog.count_accounted)
    print(paste(i, "hog count"))
  if (state_missing[state_missing$state == i, ]$cattle.count_state != state_missing[state_missing$state == i, ]$cattle.count_accounted)
    print(paste(i, "cattle count"))
  if (state_missing[state_missing$state == i, ]$sheep.count_state != state_missing[state_missing$state == i, ]$sheep.count_accounted)
    print(paste(i, "sheep count"))
  if (state_missing[state_missing$state == i, ]$broiler.count_state != state_missing[state_missing$state == i, ]$broiler.count_accounted)
    print(paste(i, "broiler count"))
  if (state_missing[state_missing$state == i, ]$layer.count_state != state_missing[state_missing$state == i, ]$layer.count_accounted)
    print(paste(i, "layer count"))
}

```

```{r}

state_missing_filled = copy(state_missing)
state_missing_filled$sheep.count_state <- as.integer(gsub(-47, 0, state_missing_filled$sheep.count_state))
state_missing_filled$hog.count_state <- as.integer(gsub(-47, 0, state_missing_filled$hog.count_state))
state_missing_filled$cattle.count_state <- as.integer(gsub(-47, 0, state_missing_filled$cattle.count_state))
state_missing_filled$layer.count_state <- as.integer(gsub(-47, 0, state_missing_filled$layer.count_state))
state_missing_filled$broiler.count_state <- as.integer(gsub(-47, 0, state_missing_filled$broiler.count_state))

state_missing_filled$hog.count_difference = state_missing_filled$hog.count_state - state_missing_filled$hog.count_accounted
state_missing_filled$sheep.count_difference = state_missing_filled$sheep.count_state - state_missing_filled$sheep.count_accounted
state_missing_filled$cattle.count_difference = state_missing_filled$cattle.count_state - state_missing_filled$cattle.count_accounted
state_missing_filled$broiler.count_difference = state_missing_filled$broiler.count_state - state_missing_filled$broiler.count_accounted
state_missing_filled$layer.count_difference = state_missing_filled$layer.count_state - state_missing_filled$layer.count_accounted

#state_missing_filled$hog.count_difference = state_missing_filled$hog.count_accounted - state_missing_filled$hog.count_state
#state_missing_filled$sheep.count_difference = state_missing_filled$sheep.count_accounted - state_missing_filled$sheep.count_state
#state_missing_filled$cattle.count_difference = state_missing_filled$cattle.count_accounted - state_missing_filled$cattle.count_state
#state_missing_filled$broiler.count_difference = state_missing_filled$broiler.count_accounted - #state_missing_filled$broiler.count_state
#state_missing_filled$layer.count_difference = state_missing_filled$layer.count_accounted - state_missing_filled$layer.count_state
head(state_missing_filled, 10)
```

```{r}

state_missing_filled$state <- tolower(state_missing_filled$state)
state_missing_filled$state <- gsub("_", " ", state_missing_filled$state)

states <- map_data("state")
states$subregion[is.na(states$subregion)] <- "none"

state_missing_filled_map <- merge(states, state_missing_filled, sort = FALSE, by.x = 'region', by.y = 'state')
state_missing_filled_map <- state_missing_filled_map[order(state_missing_filled_map$order), ]

count_variables <- c("hog.count_difference", "cattle.count_difference", "broiler.count_difference", "layer.count_difference", "sheep.count_difference")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable)  
  p <- ggplot(state_missing_filled_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get(variable))) +
    geom_path(data = state_missing_filled_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count") +
    scale_fill_gradientn(colors = c("blue", "red"),
                         values = scales::rescale(c(0, max(state_missing_filled_map[[variable]], na.rm = TRUE))),
                         na.value = "red")  
  print(p)
}
```

```{r}
usda_w_pop_and_area = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/usda_w_pop_and_area.csv")
head(usda_w_pop_and_area, 10)
```
```{r}
usda_w_pop_and_area$region <- gsub("_", " ", usda_w_pop_and_area$region)
usda_w_pop_and_area$subregion <- gsub("_", "", usda_w_pop_and_area$subregion)
usda_w_pop_and_area$subregion <- gsub("\\.", "", usda_w_pop_and_area$subregion)
usda_w_pop_and_area$subregion <- gsub(" ", "", usda_w_pop_and_area$subregion)
usda_w_pop_and_area$subregion <- gsub("'", "", usda_w_pop_and_area$subregion)
```

```{r}
neighbor_county <- read.delim("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/county_adjacency2023.txt", header = TRUE, sep = "|", dec = ".", fill = TRUE)
head(neighbor_county, 10)
```

```{r}
neighbor_county$county = sub(" County.*", "", neighbor_county$County.Name)
neighbor_county$county = tolower(sub(" Parish.*", "", neighbor_county$county))
neighbor_county$county = tolower(sub(" Planning Region.*", "", neighbor_county$county))
neighbor_county$county = tolower(sub(" city.*", "city", neighbor_county$county))
neighbor_county$state = str_extract(neighbor_county$County.Name, "[A-Z]{2}")
neighbor_county = neighbor_county[!(neighbor_county$state %in% c("HI", "AK", "DC", "OB", "AS", "GU", "MP", "PR", "VI", "CT")), ]

neighbor_county$neighboring_county = sub(" County.*", "", neighbor_county$Neighbor.Name)
neighbor_county$neighboring_county = tolower(sub(" Parish.*", "", neighbor_county$neighboring_county))
neighbor_county$neighboring_county = tolower(sub(" Planning Region.*", "", neighbor_county$neighboring_county))
neighbor_county$neighboring_county = tolower(sub(" city.*", "city", neighbor_county$neighboring_county))

neighbor_county$neighboring_state = str_extract(neighbor_county$Neighbor.Name, "[A-Z]{2}")
neighbor_county = neighbor_county[!(neighbor_county$neighboring_state %in% c("HI", "AK", "DC", "OB", "AS", "GU", "MP", "PR", "VI")), ]

state_dict = c(
  AL = "Alabama", AZ = "Arizona", AR = "Arkansas", CA = "California", CO = "Colorado",
  CT = "Connecticut", DE = "Delaware", FL = "Florida", GA = "Georgia", ID = "Idaho",
  IL = "Illinois", IN = "Indiana", IA = "Iowa", KS = "Kansas", KY = "Kentucky",
  LA = "Louisiana", ME = "Maine", MD = "Maryland", MA = "Massachusetts", MI = "Michigan",
  MN = "Minnesota", MS = "Mississippi", MO = "Missouri", MT = "Montana", NE = "Nebraska",
  NV = "Nevada", NH = "New Hampshire", NJ = "New Jersey", NM = "New Mexico", NY = "New York",
  NC = "North Carolina", ND = "North Dakota", OH = "Ohio", OK = "Oklahoma", OR = "Oregon",
  PA = "Pennsylvania", RI = "Rhode Island", SC = "South Carolina", SD = "South Dakota",
  TN = "Tennessee", TX = "Texas", UT = "Utah", VT = "Vermont", VA = "Virginia",
  WA = "Washington", WV = "West Virginia", WI = "Wisconsin", WY = "Wyoming"
)

convert_state <- function(state_code) {
  return(state_dict[[state_code]])
}
neighbor_county$state <- tolower(sapply(neighbor_county$state, convert_state))
neighbor_county$neighboring_state <- tolower(sapply(neighbor_county$neighboring_state, convert_state))
neighbor_county

neighbor_county$state <- gsub("_", " ", neighbor_county$state)
neighbor_county$county <- gsub("_", "", neighbor_county$county)
neighbor_county$county <- gsub("\\.", "", neighbor_county$county)
neighbor_county$county <- gsub(" ", "", neighbor_county$county)
neighbor_county$county <- gsub("'", "", neighbor_county$county)

neighbor_county$neighboring_state <- gsub("_", " ", neighbor_county$neighboring_state)
neighbor_county$neighboring_county <- gsub("_", "", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub("\\.", "", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub(" ", "", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub("'", "", neighbor_county$neighboring_county)

neighbor_county$county <- gsub("oglalalakota", "oglaladakota", neighbor_county$county)
neighbor_county$county <- gsub("do単aana", "donaana", neighbor_county$county)
neighbor_county$neighboring_county <- gsub("oglalalakota", "oglaladakota", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub("do単aana", "donaana", neighbor_county$neighboring_county)

write.csv(neighbor_county, "C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/neighbor_county.csv", row.names = FALSE)

```
```{r}
neighbor_county_updated = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/neighbor_county_updated.csv")
head(neighbor_county_updated, 10)
```


```{r}
neighbor_county_filtered <- neighbor_county_updated[!(neighbor_county_updated$state == neighbor_county_updated$neighboring_state & neighbor_county_updated$county == neighbor_county_updated$neighboring_county), ]

usda_w_pop_and_area_simplified = select(usda_w_pop_and_area, "region", "subregion", "Population..2020.census.", "Area..mi.2.")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]

neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)
neighboring_count_summed <- neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`))
neighboring_count_summed
```

```{r}
counties <- map_data("county")
counties$subregion[is.na(counties$subregion)] <- "none"
counties$subregion <- gsub(" ", "", counties$subregion)

county_subset_map <- merge(counties, neighboring_count_summed, sort = FALSE, by.x = c('region', 'subregion'), by.y = c('state', 'county'))
county_subset_map <- county_subset_map[order(county_subset_map$order), ]

count_variables <- c("pop_summed", "area_summed")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable) 
  p <- ggplot(county_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = ifelse(get(variable) == -47, "red", get(variable)))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count")  
  print(p)
}
```

---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ggplot2)
library(dplyr)
library(data.table)
library(sets)
library(stringr)
```

```{r}
usda_data = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/usda_data.csv")
head(usda_data, 10)
```

```{r}
# Specify the values to filter
values_to_filter <- c(2527, 1470, 2128, 973, 2431, 3022, 867, 767, 2039, 85, 2243, 1, 298, 2827, 1642, 1299, 1884, 674, 366, 1387, 571, 220, 161, 2206, 2364, 1094, 1215, 2966, 1821, 1585, 2926, 526, 1787, 2782, 1985, 2317, 69, 3095, 1176, 2812, 1159, 1736, 1200, 1765, 285, 1754, 294, 2311)

state_subset <- usda_data[usda_data$X %in% values_to_filter, ]
state_subset$state <- tolower(state_subset$state)
state_subset$state <- gsub("_", " ", state_subset$state)

county_subset <- usda_data[!(usda_data$X %in% values_to_filter), ]
county_subset$state <- tolower(county_subset$state)
county_subset$county <- tolower(county_subset$county)
county_subset$state <- gsub("_", " ", county_subset$state)
county_subset$county <- gsub("_", "", county_subset$county)
county_subset$county <- gsub("\\.", "", county_subset$county)
county_subset$county <- gsub(" ", "", county_subset$county)
county_subset$county <- gsub("'", "", county_subset$county)

```

```{r, echo=TRUE, results='markup'}
states <- map_data("state")
states$subregion[is.na(states$subregion)] <- "none"

state_subset_map <- merge(states, state_subset, sort = FALSE, by.x = 'region', by.y = 'state')
state_subset_map <- state_subset_map[order(state_subset_map$order), ]

count_variables <- c("hog.count", "cattle.count", "broiler.count", "layer.count", "sheep.count")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable) 
  p <- ggplot(state_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get(variable))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count")  
  print(p)
}
```

```{r, echo=TRUE, results='markup'}
states <- map_data("state")
states$subregion[is.na(states$subregion)] <- "none"

state_subset_map <- merge(states, state_subset, sort = FALSE, by.x = 'region', by.y = 'state')
state_subset_map <- state_subset_map[order(state_subset_map$order), ]

count_variables <- c("hog.farm", "cattle.farms", "broiler.farm", "layer.farm", "sheep.farm")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable)  
  p <- ggplot(state_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get(variable))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count") 
  print(p)
}
```

```{r}
counties <- map_data("county")
counties$subregion[is.na(counties$subregion)] <- "none"
counties$subregion <- gsub(" ", "", counties$subregion)

county_subset_map <- merge(counties, county_subset, sort = FALSE, by.x = c('region', 'subregion'), by.y = c('state', 'county'))
county_subset_map <- county_subset_map[order(county_subset_map$order), ]

count_variables <- c("hog.farm", "cattle.farms", "broiler.farm", "layer.farm", "sheep.farm")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable) 
  p <- ggplot(county_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = ifelse(get(variable) == -47, "red", get(variable)))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count")  
  print(p)
}
```

```{r}
counties <- map_data("county")
counties$subregion[is.na(counties$subregion)] <- "none"
counties$subregion <- gsub(" ", "", counties$subregion)

county_subset_map <- merge(counties, county_subset, sort = FALSE, by.x = c('region', 'subregion'), by.y = c('state', 'county'))
county_subset_map <- county_subset_map[order(county_subset_map$order), ]

count_variables <- c("hog.count", "cattle.count", "broiler.count", "layer.count", "sheep.count")

threshold <- c(1000000, 750000, 1.25*10^8 , 7500000, 50000)

for (i in 1:length(count_variables)) {
  plot_title <- gsub("\\.", " ", count_variables[i]) 
  p <- ggplot(county_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get(count_variables[i]))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count")  +
    scale_fill_gradient(name="Count", limits=c(0, threshold[i]))
  
  red_counties <- county_subset_map[county_subset_map[[variable]] == -47, ]
  p <- p + geom_polygon(data = red_counties, aes(group = group), fill = "red")
  
  max_counties <- county_subset_map[county_subset_map[[variable]] > threshold[i], ]
  p <- p + geom_polygon(data = max_counties, aes(group = group), fill = "#56B1F7")
  
  print(p)
}
```

```{r}

state_missing = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/state_missing.csv")
head(state_missing, 10)

```

```{r}
state_names = unique(state_missing$state)


for (i in state_names) {
  if (state_missing[state_missing$state == i, ]$hog.count_state != state_missing[state_missing$state == i, ]$hog.count_accounted)
    print(paste(i, "hog count"))
  if (state_missing[state_missing$state == i, ]$cattle.count_state != state_missing[state_missing$state == i, ]$cattle.count_accounted)
    print(paste(i, "cattle count"))
  if (state_missing[state_missing$state == i, ]$sheep.count_state != state_missing[state_missing$state == i, ]$sheep.count_accounted)
    print(paste(i, "sheep count"))
  if (state_missing[state_missing$state == i, ]$broiler.count_state != state_missing[state_missing$state == i, ]$broiler.count_accounted)
    print(paste(i, "broiler count"))
  if (state_missing[state_missing$state == i, ]$layer.count_state != state_missing[state_missing$state == i, ]$layer.count_accounted)
    print(paste(i, "layer count"))
}

```

```{r}

state_missing_filled = copy(state_missing)
state_missing_filled$sheep.count_state <- as.integer(gsub(-47, 0, state_missing_filled$sheep.count_state))
state_missing_filled$hog.count_state <- as.integer(gsub(-47, 0, state_missing_filled$hog.count_state))
state_missing_filled$cattle.count_state <- as.integer(gsub(-47, 0, state_missing_filled$cattle.count_state))
state_missing_filled$layer.count_state <- as.integer(gsub(-47, 0, state_missing_filled$layer.count_state))
state_missing_filled$broiler.count_state <- as.integer(gsub(-47, 0, state_missing_filled$broiler.count_state))

state_missing_filled$hog.count_difference = state_missing_filled$hog.count_state - state_missing_filled$hog.count_accounted
state_missing_filled$sheep.count_difference = state_missing_filled$sheep.count_state - state_missing_filled$sheep.count_accounted
state_missing_filled$cattle.count_difference = state_missing_filled$cattle.count_state - state_missing_filled$cattle.count_accounted
state_missing_filled$broiler.count_difference = state_missing_filled$broiler.count_state - state_missing_filled$broiler.count_accounted
state_missing_filled$layer.count_difference = state_missing_filled$layer.count_state - state_missing_filled$layer.count_accounted

#state_missing_filled$hog.count_difference = state_missing_filled$hog.count_accounted - state_missing_filled$hog.count_state
#state_missing_filled$sheep.count_difference = state_missing_filled$sheep.count_accounted - state_missing_filled$sheep.count_state
#state_missing_filled$cattle.count_difference = state_missing_filled$cattle.count_accounted - state_missing_filled$cattle.count_state
#state_missing_filled$broiler.count_difference = state_missing_filled$broiler.count_accounted - #state_missing_filled$broiler.count_state
#state_missing_filled$layer.count_difference = state_missing_filled$layer.count_accounted - state_missing_filled$layer.count_state
head(state_missing_filled, 10)
```

```{r}

state_missing_filled$state <- tolower(state_missing_filled$state)
state_missing_filled$state <- gsub("_", " ", state_missing_filled$state)

states <- map_data("state")
states$subregion[is.na(states$subregion)] <- "none"

state_missing_filled_map <- merge(states, state_missing_filled, sort = FALSE, by.x = 'region', by.y = 'state')
state_missing_filled_map <- state_missing_filled_map[order(state_missing_filled_map$order), ]

count_variables <- c("hog.count_difference", "cattle.count_difference", "broiler.count_difference", "layer.count_difference", "sheep.count_difference")

for (variable in count_variables) {
  plot_title <- gsub("\\.", " ", variable)  
  p <- ggplot(state_missing_filled_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get(variable))) +
    geom_path(data = state_missing_filled_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = plot_title, fill = "Count") +
    scale_fill_gradientn(colors = c("blue", "red"),
                         values = scales::rescale(c(0, max(state_missing_filled_map[[variable]], na.rm = TRUE))),
                         na.value = "red")  
  print(p)
}
```

```{r}
usda_w_pop_and_area = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/usda_w_pop_and_area.csv")
head(usda_w_pop_and_area, 10)
```
```{r}
usda_w_pop_and_area$region <- gsub("_", " ", usda_w_pop_and_area$region)
usda_w_pop_and_area$subregion <- gsub("_", "", usda_w_pop_and_area$subregion)
usda_w_pop_and_area$subregion <- gsub("\\.", "", usda_w_pop_and_area$subregion)
usda_w_pop_and_area$subregion <- gsub(" ", "", usda_w_pop_and_area$subregion)
usda_w_pop_and_area$subregion <- gsub("'", "", usda_w_pop_and_area$subregion)
```

```{r}
neighbor_county <- read.delim("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/county_adjacency2023.txt", header = TRUE, sep = "|", dec = ".", fill = TRUE)
head(neighbor_county, 10)
```

```{r}
neighbor_county$county = sub(" County.*", "", neighbor_county$County.Name)
neighbor_county$county = tolower(sub(" Parish.*", "", neighbor_county$county))
neighbor_county$county = tolower(sub(" Planning Region.*", "", neighbor_county$county))
neighbor_county$county = tolower(sub(" city.*", "city", neighbor_county$county))
neighbor_county$state = str_extract(neighbor_county$County.Name, "[A-Z]{2}")
neighbor_county = neighbor_county[!(neighbor_county$state %in% c("HI", "AK", "DC", "OB", "AS", "GU", "MP", "PR", "VI", "CT")), ]

neighbor_county$neighboring_county = sub(" County.*", "", neighbor_county$Neighbor.Name)
neighbor_county$neighboring_county = tolower(sub(" Parish.*", "", neighbor_county$neighboring_county))
neighbor_county$neighboring_county = tolower(sub(" Planning Region.*", "", neighbor_county$neighboring_county))
neighbor_county$neighboring_county = tolower(sub(" city.*", "city", neighbor_county$neighboring_county))

neighbor_county$neighboring_state = str_extract(neighbor_county$Neighbor.Name, "[A-Z]{2}")
neighbor_county = neighbor_county[!(neighbor_county$neighboring_state %in% c("HI", "AK", "DC", "OB", "AS", "GU", "MP", "PR", "VI")), ]

state_dict = c(
  AL = "Alabama", AZ = "Arizona", AR = "Arkansas", CA = "California", CO = "Colorado",
  CT = "Connecticut", DE = "Delaware", FL = "Florida", GA = "Georgia", ID = "Idaho",
  IL = "Illinois", IN = "Indiana", IA = "Iowa", KS = "Kansas", KY = "Kentucky",
  LA = "Louisiana", ME = "Maine", MD = "Maryland", MA = "Massachusetts", MI = "Michigan",
  MN = "Minnesota", MS = "Mississippi", MO = "Missouri", MT = "Montana", NE = "Nebraska",
  NV = "Nevada", NH = "New Hampshire", NJ = "New Jersey", NM = "New Mexico", NY = "New York",
  NC = "North Carolina", ND = "North Dakota", OH = "Ohio", OK = "Oklahoma", OR = "Oregon",
  PA = "Pennsylvania", RI = "Rhode Island", SC = "South Carolina", SD = "South Dakota",
  TN = "Tennessee", TX = "Texas", UT = "Utah", VT = "Vermont", VA = "Virginia",
  WA = "Washington", WV = "West Virginia", WI = "Wisconsin", WY = "Wyoming"
)

convert_state <- function(state_code) {
  return(state_dict[[state_code]])
}
neighbor_county$state <- tolower(sapply(neighbor_county$state, convert_state))
neighbor_county$neighboring_state <- tolower(sapply(neighbor_county$neighboring_state, convert_state))
neighbor_county

neighbor_county$state <- gsub("_", " ", neighbor_county$state)
neighbor_county$county <- gsub("_", "", neighbor_county$county)
neighbor_county$county <- gsub("\\.", "", neighbor_county$county)
neighbor_county$county <- gsub(" ", "", neighbor_county$county)
neighbor_county$county <- gsub("'", "", neighbor_county$county)

neighbor_county$neighboring_state <- gsub("_", " ", neighbor_county$neighboring_state)
neighbor_county$neighboring_county <- gsub("_", "", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub("\\.", "", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub(" ", "", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub("'", "", neighbor_county$neighboring_county)

neighbor_county$county <- gsub("oglalalakota", "oglaladakota", neighbor_county$county)
neighbor_county$county <- gsub("do単aana", "donaana", neighbor_county$county)
neighbor_county$neighboring_county <- gsub("oglalalakota", "oglaladakota", neighbor_county$neighboring_county)
neighbor_county$neighboring_county <- gsub("do単aana", "donaana", neighbor_county$neighboring_county)

write.csv(neighbor_county, "C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/neighbor_county.csv", row.names = FALSE)

```

```{r}
neighbor_county_updated = read.csv("C:/Users/reese/OneDrive/Documents/Research/Mom project 1/Data/neighbor_county_updated.csv")
head(neighbor_county_updated, 10)
```


```{r}
neighbor_county_filtered <- neighbor_county_updated[!(neighbor_county_updated$state == neighbor_county_updated$neighboring_state & neighbor_county_updated$county == neighbor_county_updated$neighboring_county), ]

usda_w_pop_and_area_simplified = select(usda_w_pop_and_area, "region", 
                                        "subregion", 
                                        "Population..2020.census.", 
                                        "Area..mi.2.",
                                        "cattle.farms",
                                        "cattle.count",
                                        "hog.farm",
                                        "hog.count",
                                        "sheep.farm",
                                        "sheep.count",
                                        "broiler.farm",
                                        "broiler.count",
                                        "layer.farm",
                                        "layer.count")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]

neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

neighboring_count$sheep.count <- as.integer(gsub(-47, 0, neighboring_count$sheep.count))
neighboring_count$hog.count <- as.integer(gsub(-47, 0, neighboring_count$hog.count))
neighboring_count$cattle.count <- as.integer(gsub(-47, 0, neighboring_count$cattle.count))
neighboring_count$layer.count <- as.integer(gsub(-47, 0, neighboring_count$layer.count))
neighboring_count$broiler.count <- as.integer(gsub(-47, 0, neighboring_count$broiler.count))

neighboring_count$sheep.count[is.na(neighboring_count$sheep.count)] <- 0
neighboring_count$hog.count[is.na(neighboring_count$hog.count)] <- 0
neighboring_count$cattle.count[is.na(neighboring_count$cattle.count)] <- 0
neighboring_count$layer.count[is.na(neighboring_count$layer.count)] <- 0
neighboring_count$broiler.count[is.na(neighboring_count$broiler.count)] <- 0

neighboring_count_summed <- neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )
neighboring_count_summed$county <- gsub("oglaladakota", "oglalalakota", neighboring_count_summed$county)
neighboring_count_summed
```

```{r}
linear_model_data = merge(
  neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data = merge(
  linear_model_data,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

head(linear_model_data, 10)
```
## LOOK HERE MOM

```{r}
linear_model_sheep_data = linear_model_data[linear_model_data$sheep.count.x != -47, ]
linear_model_sheep_data = linear_model_sheep_data[complete.cases(linear_model_sheep_data["state"]), ]
linear_model_sheep = glm(sheep.count.x ~ pop_summed + area_summed + sheep_count_summed + Population..2020.census. + Area..mi.2. + sheep.farm.x + sheep.count.y,  family="poisson", data = linear_model_sheep_data)
stargazer(
  linear_model_sheep,
  type = 'text', 
  covariate.labels = c(
    'Surrounding Population', 'Surrounding Area', 'Surrounding Sheep Count', "County Population", "County Area", "Sheep Farms", "Total State Sheep Count"
    )
)

```
```{r}
linear_model_data[linear_model_data$sheep.count.x == -47, ]
```

```{r}
testing_sheep_data = linear_model_data[linear_model_data$sheep.count.x == -47, ]
predicting_sheep_data = testing_sheep_data[ , !(names(testing_sheep_data) == "sheep.count.x")]

predicting_sheep_data$sheep.count.x = predict(linear_model_sheep, newdata = predicting_sheep_data)
predicting_sheep_data = predicting_sheep_data[complete.cases(predicting_sheep_data["state"]), ]
predicting_sheep_data
```

```{r}

concat = rbind(linear_model_sheep_data, predicting_sheep_data)

counties <- map_data("county")
counties$subregion[is.na(counties$subregion)] <- "none"
counties$subregion <- gsub(" ", "", counties$subregion)

county_subset_map <- merge(counties, concat, sort = FALSE, by.x = c('region', 'subregion'), by.y = c('state', 'county.x'), all = TRUE)
county_subset_map <- county_subset_map[order(county_subset_map$order), ]

count_variables <- c("hog.count", "cattle.count", "broiler.count", "layer.count", "sheep.count")

plot_title <- gsub("\\.", " ", count_variables["sheep.count.x"]) 
p <- ggplot(county_subset_map, aes(long, lat)) +
  geom_polygon(aes(group = group, fill = get("sheep.count.x"))) +
  geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
  coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
  labs(title = "Sheep Count Filled", fill = "Count")  

print(p)

```

```{r}
linear_model_cow_data = linear_model_data[linear_model_data$cattle.count.x != -47, ]
linear_model_cow_data = linear_model_cow_data[complete.cases(linear_model_cow_data["state"]), ]
linear_model_cow = glm(cattle.count.x ~ pop_summed + area_summed + cattle_count_summed + Population..2020.census. + Area..mi.2. + cattle.farms.x, family="poisson", data = linear_model_cow_data)
stargazer(
  linear_model_cow,
  type = 'text', 
  covariate.labels = c(
    'Surrounding Population', 'Surrounding Area', 'Surrounding Cow', "County Population", "County Area", "Cattle Farms"
    )
)
```
```{r}
testing_cow_data = linear_model_data[linear_model_data$cattle.count == -47, ]
predicting_cow_data = testing_cow_data[ , !(names(testing_cow_data) == "cattle.count.x")]

predicting_cow_data$cattle.count.x = predict(linear_model_cow, newdata = predicting_cow_data)
predicting_cow_data = predicting_cow_data[complete.cases(predicting_cow_data["state"]), ]
predicting_sheep_data
```
```{r}

concat = rbind(linear_model_cow_data, predicting_cow_data)

counties <- map_data("county")
counties$subregion[is.na(counties$subregion)] <- "none"
counties$subregion <- gsub(" ", "", counties$subregion)

county_subset_map <- merge(counties, concat, sort = FALSE, by.x = c('region', 'subregion'), by.y = c('state', 'county.x'), all = TRUE)
county_subset_map <- county_subset_map[order(county_subset_map$order), ]

count_variables <- c("hog.count", "cattle.count", "broiler.count", "layer.count", "sheep.count")

  plot_title <- gsub("\\.", " ", count_variables["cattle.count.x"]) 
  p <- ggplot(county_subset_map, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = get("cattle.count.x"))) +
    geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
    coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
    labs(title = "Cattle Count Filled", fill = "Count")  
  
  print(p)
```
```{r}
library(MASS)

linear_model_sheep_data = linear_model_data[linear_model_data$sheep.count.x != -47, ]
linear_model_sheep_data = linear_model_sheep_data[complete.cases(linear_model_sheep_data["state"]), ]
linear_model_sheep = glm.nb(sheep.count.x ~ pop_summed + area_summed + sheep_count_summed + Population..2020.census. + Area..mi.2. + sheep.farm.x + sheep.count.y,  data = linear_model_sheep_data, maxit = 1000)
stargazer(
  linear_model_sheep,
  type = 'text', 
  covariate.labels = c(
    'Surrounding Population', 'Surrounding Area', 'Surrounding Sheep Count', "County Population", "County Area", "Sheep Farms", "Total State Sheep Count"
    )
)

testing_sheep_data = linear_model_data[linear_model_data$sheep.count.x == -47, ]
predicting_sheep_data = testing_sheep_data[ , !(names(testing_sheep_data) == "sheep.count.x")]

predicting_sheep_data$sheep.count.x = predict(linear_model_sheep, newdata = predicting_sheep_data, type = "response")
predicting_sheep_data = predicting_sheep_data[complete.cases(predicting_sheep_data["state"]), ]
predicting_sheep_data
```
```{r}
concat = rbind(linear_model_sheep_data, predicting_sheep_data)

counties <- map_data("county")
counties$subregion[is.na(counties$subregion)] <- "none"
counties$subregion <- gsub(" ", "", counties$subregion)

county_subset_map <- merge(counties, concat, sort = FALSE, by.x = c('region', 'subregion'), by.y = c('state', 'county.x'), all = TRUE)
county_subset_map <- county_subset_map[order(county_subset_map$order), ]

count_variables <- c("hog.count", "cattle.count", "broiler.count", "layer.count", "sheep.count")

plot_title <- gsub("\\.", " ", count_variables["sheep.count.x"]) 
p <- ggplot(county_subset_map, aes(long, lat)) +
  geom_polygon(aes(group = group, fill = get("sheep.count.x"))) +
  geom_path(data = state_subset_map, aes(long, lat, group = group), color = "black") +
  coord_map("albers",  lat0 = 45.5, lat1 = 29.5) +
  labs(title = "Sheep Count Filled", fill = "Count")  

print(p)
```
```{r}
neighbor_county_filtered <- neighbor_county_updated[!(neighbor_county_updated$state == neighbor_county_updated$neighboring_state & neighbor_county_updated$county == neighbor_county_updated$neighboring_county), ]

usda_w_pop_and_area_simplified = select(usda_w_pop_and_area, "region", 
                                        "subregion", 
                                        "Population..2020.census.", 
                                        "Area..mi.2.",
                                        "cattle.farms",
                                        "cattle.count",
                                        "hog.farm",
                                        "hog.count",
                                        "sheep.farm",
                                        "sheep.count",
                                        "broiler.farm",
                                        "broiler.count",
                                        "layer.farm",
                                        "layer.count")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]

neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

neighboring_count$sheep.count <- as.integer(gsub(-47, 0, neighboring_count$sheep.count))
neighboring_count$Area..mi.2. <- ifelse(neighboring_count$sheep.count == 0, 0, neighboring_count$Area..mi.2.)

neighboring_count$sheep.count[is.na(neighboring_count$sheep.count)] <- 0


neighboring_count_summed <- neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )
neighboring_count_summed$county <- gsub("oglaladakota", "oglalalakota", neighboring_count_summed$county)
neighboring_count_summed
```

