---
title: "Linear CAFO Data CSV Generator"
output: html_document
date: "2025-12-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(data.table)
library(sets)
library(stringr)
library(tidyr)
library(stargazer)
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
```

```{r}
usda_data = read.csv("../Data/Scraped Data/2022_cafo/usda_cafo_2022_cleaned.csv")
head(usda_data, 10)
neighbor_county_updated = read.csv("../Data/neighbor_county_updated.csv")
neighbor_county_updated <- neighbor_county_updated[
  !(neighbor_county_updated$county == neighbor_county_updated$neighboring_county & 
    neighbor_county_updated$state == neighbor_county_updated$neighboring_state), ]
head(neighbor_county_updated, 10)

values_to_filter <- c(2527, 1470, 2128, 973, 2431, 3022, 867, 767, 2039, 85, 2243, 1, 298, 2827, 1642, 1299, 1884, 674, 366, 1387, 571, 220, 161, 2206, 2364, 1094, 1215, 2966, 1821, 1585, 2926, 526, 1787, 2782, 1985, 2317, 69, 3095, 1176, 2812, 1159, 1736, 1200, 1765, 285, 1754, 294, 2311)

state_subset <- usda_data[values_to_filter, ]
state_subset$STATE <- tolower(state_subset$STATE)
state_subset$STATE <- gsub("_", " ", state_subset$STATE)
state_subset[is.na(state_subset)] <- 0
```
```{r}

usda_w_pop_and_area = read.csv("../Data/usda_w_pop_and_area.csv")
head(usda_w_pop_and_area, 10)

neighbor_county_filtered <- neighbor_county_updated[!(neighbor_county_updated$state == neighbor_county_updated$neighboring_state & neighbor_county_updated$county == neighbor_county_updated$neighboring_county), ]

usda_w_pop_and_area_simplified = dplyr::select(usda_w_pop_and_area, "region", "subregion", "Population..2020.census.", "Area..mi.2.")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]
neighbor_county_updated <- subset(neighbor_county_updated, county != "buenavistacity")
neighbor_county_updated <- subset(neighbor_county_updated, neighboring_county != "buenavistacity")


neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)
neighboring_count_summed <- neighboring_count %>%
  group_by(state, county) %>%
  summarise(
    pop_summed = sum(Population..2020.census., na.rm = TRUE),
    area_summed = sum(Area..mi.2., na.rm = TRUE)
  )

```
```{r}
usda_data_clean <- usda_data[-values_to_filter, ]
usda_data_clean$COUNTY = gsub("'", "", usda_data_clean$COUNTY)
usda_data_clean$COUNTY <- gsub(".", "", usda_data_clean$COUNTY, fixed = TRUE)
usda_data_clean$STATE = gsub("_", " ", usda_data_clean$STATE)
usda_data_clean$COUNTY = gsub("virginiabeachcity", "virginiabeach", usda_data_clean$COUNTY)
usda_data_clean$COUNTY = gsub("oglalalakota", "oglaladakota", usda_data_clean$COUNTY)

usda_data_clean$STATE  <- tolower(usda_data_clean$STATE)
usda_data_clean$COUNTY <- tolower(usda_data_clean$COUNTY)
```

```{r}
usda_w_pop_and_area_cleaned =  merge(
  usda_data_clean,
  usda_w_pop_and_area_simplified, 
  by.x = c('STATE', 'COUNTY'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

usda_w_pop_and_area_cleaned <- usda_w_pop_and_area_cleaned[!is.na(usda_w_pop_and_area_cleaned$Population..2020.census.), ]


usda_w_pop_and_area_cleaned = usda_w_pop_and_area_cleaned[!duplicated(usda_w_pop_and_area_cleaned), ]
usda_w_pop_and_area_cleaned[is.na(usda_w_pop_and_area_cleaned)] <- 0

neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_cleaned, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('STATE', 'COUNTY'),
  all = TRUE  
)

neighboring_count$HOG2022NUM <- as.integer(gsub(-47, 0, neighboring_count$HOG2022NUM))
neighboring_count$BRL2022NUM <- as.integer(gsub(-47, 0, neighboring_count$BRL2022NUM))
neighboring_count$LAY2022NUM <- as.integer(gsub(-47, 0, neighboring_count$LAY2022NUM))
neighboring_count$COW2022NUM <- as.integer(gsub(-47, 0, neighboring_count$COW2022NUM))
neighboring_count$DRY2022NUM <- as.integer(gsub(-47, 0, neighboring_count$DRY2022NUM))


neighboring_count$HOG2022NUM[is.na(neighboring_count$HOG2022NUM)] <- 0
neighboring_count$BRL2022NUM[is.na(neighboring_count$BRL2022NUM)] <- 0
neighboring_count$LAY2022NUM[is.na(neighboring_count$LAY2022NUM)] <- 0
neighboring_count$COW2022NUM[is.na(neighboring_count$COW2022NUM)] <- 0
neighboring_count$DRY2022NUM[is.na(neighboring_count$DRY2022NUM)] <- 0


neighboring_count$HOG2022FAC[is.na(neighboring_count$HOG2022FAC)] <- 0
neighboring_count$BRL2022FAC[is.na(neighboring_count$BRL2022FAC)] <- 0
neighboring_count$LAY2022FAC[is.na(neighboring_count$LAY2022FAC)] <- 0
neighboring_count$COW2022FAC[is.na(neighboring_count$COW2022FAC)] <- 0
neighboring_count$COW2022FAC[is.na(neighboring_count$COW2022FAC)] <- 0


```

```{r}
# Load built-in FIPS reference from tidycensus
data("fips_codes")

# Load CDL crop raster summary (county-lvel pixel counts)
cdl_df <- read.csv(file = "../Data/county_pixel_count_2024_10.csv") %>% 
  rename(fips = Fips) %>%
  mutate(fips = sprintf("%05d", as.integer(fips)))

# Build FIPS lookup table (state and county names)
fips_lookup <- fips_codes %>%
  mutate(fips = paste0(state_code, county_code)) %>%
  dplyr::select(fips, state = state_name, county) %>%
  mutate(
    state = tolower(state),
    county = tolower(gsub("county", "", county)),
    county = gsub("[[:space:][:punct:]]", "", county)
  )
fips_lookup <- fips_lookup %>%
  filter(!county %in% c("bedfordcity", "fairfaxcity", "franklincity", 'richmondcity',"roanokecity"))


# Merge CDL pixel counts with cleaned state and county names
cdl_named_df <- cdl_df %>%
  left_join(fips_lookup, by = "fips")

cdl_named_df$county <- gsub("county", "", cdl_named_df$county) 
cdl_named_df$county <- gsub("parish", "", cdl_named_df$county) 
cdl_named_df$county <- gsub("miamidade", "miami-dade", cdl_named_df$county) 
cdl_named_df$county <- ifelse(
  cdl_named_df$state == "virginia" &
    !tolower(cdl_named_df$county) %in% c("jamescity", "charlescity"),
  gsub("city", "", cdl_named_df$county, ignore.case = TRUE),
  cdl_named_df$county
)

# Define CDL crop categories (skip non-agricultural land types)
crop_categories <- c(
  1:6, 10:14, 21:60, 66:77
)

# Build matching column names
crop_columns <- paste0("Category_", sprintf("%03d", crop_categories))

# Add total_crop column (safely skips missing columns)
cdl_named_df <- cdl_named_df %>%
  mutate(total_crop = rowSums(across(any_of(crop_columns)), na.rm = TRUE),
         total_crop_fraction = rowSums(across(any_of(crop_columns)), na.rm = TRUE))
  

cdl_named_df <- dplyr::select(cdl_named_df,
                              state,
                              county,
                              Category_001,
                              Category_005,
                              Category_036,
                              total_crop,
                              total_crop_fraction)

colnames(cdl_named_df) = c('state',
                           'county',
                           'corn_fraction',
                           'soy_fraction',
                           "alfalfa_fraction",
                           'total_crop',
                           'total_crop_fraction')

# Add state-level totals for all crops + major crops
cdl_named_df <- cdl_named_df %>%
  group_by(state) %>%
  mutate(
    state_total_crop     = sum(total_crop, na.rm = TRUE),
    state_total_corn     = sum(corn_fraction, na.rm = TRUE),
    state_total_soy      = sum(soy_fraction, na.rm = TRUE),
    state_total_alfalfa  = sum(alfalfa_fraction, na.rm = TRUE),
    state_total_fraction    = sum(total_crop, na.rm = TRUE),
  ) %>%
  ungroup()

```

```{r}
dairy_neighboring_count = neighboring_count

dairy_neighboring_count_summed <- dairy_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(Population..2020.census.),
            area_summed = sum(Area..mi.2.),
            cattle_farms_summed = sum(COW2022FAC),
            cattle_count_summed = sum(COW2022NUM),
            dairy_farms_summed = sum(DRY2022FAC),
            dairy_count_summed = sum(DRY2022NUM),
            broiler_farms_summed = sum(BRL2022FAC),
            broiler_count_summed = sum(BRL2022NUM),
            layer_farms_summed = sum(LAY2022FAC),
            layer_count_summed = sum(LAY2022NUM),
            hog_farms_summed = sum(HOG2022FAC),
            hog_count_summed = sum(HOG2022NUM)
            )

linear_model_data_dairy = merge(
  dairy_neighboring_count_summed,
  usda_w_pop_and_area_cleaned, 
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTY'),
  all = TRUE  
)

linear_model_data_dairy = merge(
  linear_model_data_dairy,
  state_subset,
  by.x = c('state'),
  by.y = c('STATE')
)

linear_model_data_dairy$surrounding_population_density = linear_model_data_dairy$pop_summed / linear_model_data_dairy$area_summed
linear_model_data_dairy$population_density = linear_model_data_dairy$Population..2020.census. / linear_model_data_dairy$Area..mi.2.
linear_model_data_dairy$county <- gsub("oglaladakota", "oglalalakota", linear_model_data_dairy$county)
linear_model_data_dairy$animal_density <- linear_model_data_dairy$DRY2022NUM.x / linear_model_data_dairy$Area..mi.2.
linear_model_data_dairy$surrounding_animal_density <- linear_model_data_dairy$dairy_count_summed / linear_model_data_dairy$area_summed
linear_model_data_dairy$surrounding_farm_density <- linear_model_data_dairy$hog_farms_summed / linear_model_data_dairy$area_summed
linear_model_data_dairy$farm_density <- linear_model_data_dairy$DRY2022FAC.x / linear_model_data_dairy$Area..mi.2.

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_dairy = merge(
  linear_model_data_dairy,
  county_temperature,
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTYNAME')
  )

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               
county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))
                                 
linear_model_data_dairy = merge(
  linear_model_data_dairy,
  county_income,
  by.x = c('state', 'county'),
  by.y = c('State', 'County')
  )    

linear_model_data_dairy = merge(
  linear_model_data_dairy,
  cdl_named_df,
  by.x = c('state', 'county'),
  by.y = c('state', 'county')
  , all = TRUE
  )

linear_model_data_dairy <- linear_model_data_dairy[complete.cases(linear_model_data_dairy), ]


# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_dairy[[col]] <- linear_model_data_dairy[[col]] * 0.000247105 * 100 / (linear_model_data_dairy$Area..mi.2. * 640)
}


linear_model_data_dairy = dplyr::select(linear_model_data_dairy, 
                                        "state", 
                                        "county", 
                                        "pop_summed", 
                                        "area_summed",
                                        "cattle_farms_summed",
                                        "cattle_count_summed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "DRY2022FAC.x",
                                        "DRY2022NUM.x",
                                        "DRY2022FAC.y",
                                        "DRY2022NUM.y",
                                       "surrounding_population_density", 
                                       "population_density",
                                       "animal_density",
                                       "farm_density",
                                       "surrounding_animal_density",
                                       "surrounding_farm_density",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')
colnames(linear_model_data_dairy) = c(   "State", 
                                        "County", 
                                        "surroundingPopulationSummed", 
                                        "surroundingAreaSummed",
                                        "surroundingDairyFarmsSummed",
                                        "surroundingDairyCountSummed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "dairyFarms",
                                        "dairyCount",
                                        "stateDairyFarms",
                                        "stateDairyCount",
                                      "surroundingPopulationDensity", 
                                      "populationDensity",
                                      "animalDensity",
                                      "farmDensity",
                                      "surroundAnimalDensity",
                                      "surroundingFarmDensity",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')

write.csv(linear_model_data_dairy, "../Data/Animal Linear Model Data/linear_model_data_dairy_cafo.csv", row.names = FALSE)


head(linear_model_data_dairy, 10)
```

```{r}
beef_neighboring_count = neighboring_count

beef_neighboring_count_summed <- beef_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(Population..2020.census.),
            area_summed = sum(Area..mi.2.),
            cattle_farms_summed = sum(COW2022FAC),
            cattle_count_summed = sum(COW2022NUM),
            dairy_farms_summed = sum(DRY2022FAC),
            dairy_count_summed = sum(DRY2022NUM),
            broiler_farms_summed = sum(BRL2022FAC),
            broiler_count_summed = sum(BRL2022NUM),
            layer_farms_summed = sum(LAY2022FAC),
            layer_count_summed = sum(LAY2022NUM),
            hog_farms_summed = sum(HOG2022FAC),
            hog_count_summed = sum(HOG2022NUM)
            )

linear_model_data_beef = merge(
  beef_neighboring_count_summed,
  usda_w_pop_and_area_cleaned, 
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTY'),
  all = TRUE  
)

linear_model_data_beef = merge(
  linear_model_data_beef,
  state_subset,
  by.x = c('state'),
  by.y = c('STATE')
)

linear_model_data_beef$surrounding_population_density = linear_model_data_beef$pop_summed / linear_model_data_beef$area_summed
linear_model_data_beef$population_density = linear_model_data_beef$Population..2020.census. / linear_model_data_beef$Area..mi.2.
linear_model_data_beef$county <- gsub("oglaladakota", "oglalalakota", linear_model_data_beef$county)
linear_model_data_beef$animal_density <- linear_model_data_beef$COW2022NUM.x / linear_model_data_beef$Area..mi.2.
linear_model_data_beef$surrounding_animal_density <- linear_model_data_beef$cattle_count_summed / linear_model_data_beef$area_summed
linear_model_data_beef$surrounding_farm_density <- linear_model_data_beef$hog_farms_summed / linear_model_data_beef$area_summed
linear_model_data_beef$farm_density <- linear_model_data_beef$COW2022FAC.x / linear_model_data_beef$Area..mi.2.


county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_beef = merge(
  linear_model_data_beef,
  county_temperature,
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTYNAME')
  )

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               
county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))
                                 
linear_model_data_beef = merge(
  linear_model_data_beef,
  county_income,
  by.x = c('state', 'county'),
  by.y = c('State', 'County')
  )    

linear_model_data_beef = merge(
  linear_model_data_beef,
  cdl_named_df,
  by.x = c('state', 'county'),
  by.y = c('state', 'county')
  , all = TRUE
  )

linear_model_data_beef <- linear_model_data_beef[complete.cases(linear_model_data_beef), ]


# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_beef[[col]] <- linear_model_data_beef[[col]] * 0.000247105 * 100 / (linear_model_data_beef$Area..mi.2. * 640)
}


linear_model_data_beef = dplyr::select(linear_model_data_beef, 
                                        "state", 
                                        "county", 
                                        "pop_summed", 
                                        "area_summed",
                                        "cattle_farms_summed",
                                        "cattle_count_summed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "COW2022FAC.x",
                                        "COW2022NUM.x",
                                        "COW2022FAC.y",
                                        "COW2022NUM.y",
                                       "surrounding_population_density", 
                                       "population_density",
                                       "animal_density",
                                       "farm_density",
                                       "surrounding_animal_density",
                                       "surrounding_farm_density",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')
colnames(linear_model_data_beef) = c( "State", 
                                        "County", 
                                        "surroundingPopulationSummed", 
                                        "surroundingAreaSummed",
                                        "surroundingBeefFarmsSummed",
                                        "surroundingBeefCountSummed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "beefFarms",
                                        "beefCount",
                                        "stateBeefFarms",
                                        "stateBeefCount",
                                      "surroundingPopulationDensity", 
                                      "populationDensity",
                                      "animalDensity",
                                      "farmDensity",
                                      "surroundAnimalDensity",
                                      "surroundingFarmDensity",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')

write.csv(linear_model_data_beef, "../Data/Animal Linear Model Data/linear_model_data_beef_cafo.csv", row.names = FALSE)


head(linear_model_data_beef, 10)
```
```{r}
hog_neighboring_count = neighboring_count

hog_neighboring_count_summed <- hog_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(Population..2020.census.),
            area_summed = sum(Area..mi.2.),
            cattle_farms_summed = sum(COW2022FAC),
            cattle_count_summed = sum(COW2022NUM),
            dairy_farms_summed = sum(DRY2022FAC),
            dairy_count_summed = sum(DRY2022NUM),
            broiler_farms_summed = sum(BRL2022FAC),
            broiler_count_summed = sum(BRL2022NUM),
            layer_farms_summed = sum(LAY2022FAC),
            layer_count_summed = sum(LAY2022NUM),
            hog_farms_summed = sum(HOG2022FAC),
            hog_count_summed = sum(HOG2022NUM)
  )

linear_model_data_hog = merge(
  hog_neighboring_count_summed,
  usda_w_pop_and_area_cleaned, 
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTY'),
  all = TRUE  
)

linear_model_data_hog = merge(
  linear_model_data_hog,
  state_subset,
  by.x = c('state'),
  by.y = c('STATE')
)

linear_model_data_hog$surrounding_population_density = linear_model_data_hog$pop_summed / linear_model_data_hog$area_summed
linear_model_data_hog$population_density = linear_model_data_hog$Population..2020.census. / linear_model_data_hog$Area..mi.2.
linear_model_data_hog$county <- gsub("oglaladakota", "oglalalakota", linear_model_data_hog$county)
linear_model_data_hog$animal_density <- linear_model_data_hog$HOG2022NUM.x / linear_model_data_hog$Area..mi.2.
linear_model_data_hog$surrounding_animal_density <- linear_model_data_hog$hog_count_summed / linear_model_data_hog$area_summed
linear_model_data_hog$surrounding_farm_density <- linear_model_data_hog$hog_farms_summed / linear_model_data_hog$area_summed
linear_model_data_hog$farm_density <- linear_model_data_hog$HOG2022FAC.x / linear_model_data_hog$Area..mi.2.

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_hog = merge(
  linear_model_data_hog,
  county_temperature,
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTYNAME')
)

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               
county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))

linear_model_data_hog = merge(
  linear_model_data_hog,
  county_income,
  by.x = c('state', 'county'),
  by.y = c('State', 'County')
)    

linear_model_data_hog = merge(
  linear_model_data_hog,
  cdl_named_df,
  by.x = c('state', 'county'),
  by.y = c('state', 'county')
  , all = TRUE
)

linear_model_data_hog <- linear_model_data_hog[complete.cases(linear_model_data_hog), ]


# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_hog[[col]] <- linear_model_data_hog[[col]] * 0.000247105 * 100 / (linear_model_data_hog$Area..mi.2. * 640)
}


linear_model_data_hog = dplyr::select(linear_model_data_hog, 
                                       "state", 
                                       "county", 
                                       "pop_summed", 
                                       "area_summed",
                                       "hog_farms_summed",
                                       "hog_count_summed",
                                       "Population..2020.census.",
                                       "Area..mi.2.",
                                       "HOG2022FAC.x",
                                       "HOG2022NUM.x",
                                       "HOG2022FAC.y",
                                       "HOG2022NUM.y",
                                       "surrounding_population_density", 
                                       "population_density",
                                       "animal_density",
                                       "farm_density",
                                       "surrounding_animal_density",
                                       "surrounding_farm_density",
                                       "Cooling.Degree.Days_JAN", 
                                       "Heating.Degree.Days_JAN", 
                                       "pcp_JAN", 
                                       "tavg_JAN", 
                                       "tmax_JAN", 
                                       "tmin_JAN", 
                                       "Cooling.Degree.Days_FEB", 
                                       "Heating.Degree.Days_FEB", 
                                       "pcp_FEB", 
                                       "tavg_FEB", 
                                       "tmax_FEB", 
                                       "tmin_FEB", 
                                       "Cooling.Degree.Days_MAR", 
                                       "Heating.Degree.Days_MAR", 
                                       "pcp_MAR", 
                                       "tavg_MAR", 
                                       "tmax_MAR", 
                                       "tmin_MAR",
                                       "Cooling.Degree.Days_APR",       
                                       "Heating.Degree.Days_APR", 
                                       "pcp_APR", 
                                       "tavg_APR", 
                                       "tmax_APR", 
                                       "tmin_APR",
                                       "Cooling.Degree.Days_MAY", 
                                       "Heating.Degree.Days_MAY", 
                                       "pcp_MAY", 
                                       "tavg_MAY", 
                                       "tmax_MAY", 
                                       "tmin_MAY", 
                                       "Cooling.Degree.Days_JUN", 
                                       "Heating.Degree.Days_JUN", 
                                       "pcp_JUN", 
                                       "tavg_JUN",                       
                                       "tmax_JUN",
                                       "tmin_JUN",
                                       "Cooling.Degree.Days_JUL", 
                                       "Heating.Degree.Days_JUL", 
                                       "pcp_JUL", 
                                       "tavg_JUL", 
                                       "tmax_JUL", 
                                       "tmin_JUL", 
                                       "Cooling.Degree.Days_AUG", 
                                       "Heating.Degree.Days_AUG", 
                                       "pcp_AUG", 
                                       "tavg_AUG", 
                                       "tmax_AUG", 
                                       "tmin_AUG",
                                       "Cooling.Degree.Days_SEP", 
                                       "Heating.Degree.Days_SEP", 
                                       "pcp_SEP", 
                                       "tavg_SEP", 
                                       "tmax_SEP", 
                                       "tmin_SEP",
                                       "Cooling.Degree.Days_OCT", 
                                       "Heating.Degree.Days_OCT", 
                                       "pcp_OCT", 
                                       "tavg_OCT", 
                                       "tmax_OCT", 
                                       "tmin_OCT",
                                       "Cooling.Degree.Days_NOV", 
                                       "Heating.Degree.Days_NOV", 
                                       "pcp_NOV", 
                                       "tavg_NOV", 
                                       "tmax_NOV", 
                                       "tmin_NOV",
                                       "Cooling.Degree.Days_DEC", 
                                       "Heating.Degree.Days_DEC", 
                                       "pcp_DEC", 
                                       "tavg_DEC", 
                                       "tmax_DEC", 
                                       "tmin_DEC",
                                       "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')
colnames(linear_model_data_hog) = c( "State", 
                                      "County", 
                                      "surroundingPopulationSummed", 
                                      "surroundingAreaSummed",
                                      "surroundingHogFarmsSummed",
                                      "surroundingHogCountSummed",
                                      "Population..2020.census.",
                                      "Area..mi.2.",
                                      "hogFarms",
                                      "hogCount",
                                      "stateHogFarms",
                                      "stateHogCount",
                                      "surroundingPopulationDensity", 
                                      "populationDensity",
                                      "animalDensity",
                                      "farmDensity",
                                      "surroundAnimalDensity",
                                      "surroundingFarmDensity",
                                      "Cooling.Degree.Days_JAN", 
                                      "Heating.Degree.Days_JAN", 
                                      "pcp_JAN", 
                                      "tavg_JAN", 
                                      "tmax_JAN", 
                                      "tmin_JAN", 
                                      "Cooling.Degree.Days_FEB", 
                                      "Heating.Degree.Days_FEB", 
                                      "pcp_FEB", 
                                      "tavg_FEB", 
                                      "tmax_FEB", 
                                      "tmin_FEB", 
                                      "Cooling.Degree.Days_MAR", 
                                      "Heating.Degree.Days_MAR", 
                                      "pcp_MAR", 
                                      "tavg_MAR", 
                                      "tmax_MAR", 
                                      "tmin_MAR",
                                      "Cooling.Degree.Days_APR",       
                                      "Heating.Degree.Days_APR", 
                                      "pcp_APR", 
                                      "tavg_APR", 
                                      "tmax_APR", 
                                      "tmin_APR",
                                      "Cooling.Degree.Days_MAY", 
                                      "Heating.Degree.Days_MAY", 
                                      "pcp_MAY", 
                                      "tavg_MAY", 
                                      "tmax_MAY", 
                                      "tmin_MAY", 
                                      "Cooling.Degree.Days_JUN", 
                                      "Heating.Degree.Days_JUN", 
                                      "pcp_JUN", 
                                      "tavg_JUN",                       
                                      "tmax_JUN",
                                      "tmin_JUN",
                                      "Cooling.Degree.Days_JUL", 
                                      "Heating.Degree.Days_JUL", 
                                      "pcp_JUL", 
                                      "tavg_JUL", 
                                      "tmax_JUL", 
                                      "tmin_JUL", 
                                      "Cooling.Degree.Days_AUG", 
                                      "Heating.Degree.Days_AUG", 
                                      "pcp_AUG", 
                                      "tavg_AUG", 
                                      "tmax_AUG", 
                                      "tmin_AUG",
                                      "Cooling.Degree.Days_SEP", 
                                      "Heating.Degree.Days_SEP", 
                                      "pcp_SEP", 
                                      "tavg_SEP", 
                                      "tmax_SEP", 
                                      "tmin_SEP",
                                      "Cooling.Degree.Days_OCT", 
                                      "Heating.Degree.Days_OCT", 
                                      "pcp_OCT", 
                                      "tavg_OCT", 
                                      "tmax_OCT", 
                                      "tmin_OCT",
                                      "Cooling.Degree.Days_NOV", 
                                      "Heating.Degree.Days_NOV", 
                                      "pcp_NOV", 
                                      "tavg_NOV", 
                                      "tmax_NOV", 
                                      "tmin_NOV",
                                      "Cooling.Degree.Days_DEC", 
                                      "Heating.Degree.Days_DEC", 
                                      "pcp_DEC", 
                                      "tavg_DEC", 
                                      "tmax_DEC", 
                                      "tmin_DEC",
                                      "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')

write.csv(linear_model_data_hog, "../Data/Animal Linear Model Data/linear_model_data_hog_cafo.csv", row.names = FALSE)


head(linear_model_data_hog, 10)
```

```{r}
broiler_neighboring_count = neighboring_count

broiler_neighboring_count_summed <- broiler_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(Population..2020.census.),
            area_summed = sum(Area..mi.2.),
            cattle_farms_summed = sum(COW2022FAC),
            cattle_count_summed = sum(COW2022NUM),
            dairy_farms_summed = sum(DRY2022FAC),
            dairy_count_summed = sum(DRY2022NUM),
            broiler_farms_summed = sum(BRL2022FAC),
            broiler_count_summed = sum(BRL2022NUM),
            layer_farms_summed = sum(LAY2022FAC),
            layer_count_summed = sum(LAY2022NUM),
            hog_farms_summed = sum(HOG2022FAC),
            hog_count_summed = sum(HOG2022NUM)
  )

linear_model_data_broiler = merge(
  broiler_neighboring_count_summed,
  usda_w_pop_and_area_cleaned, 
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTY'),
  all = TRUE  
)

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  state_subset,
  by.x = c('state'),
  by.y = c('STATE')
)

linear_model_data_broiler$surrounding_population_density = linear_model_data_broiler$pop_summed / linear_model_data_broiler$area_summed
linear_model_data_broiler$population_density = linear_model_data_broiler$Population..2020.census. / linear_model_data_broiler$Area..mi.2.
linear_model_data_broiler$county <- gsub("oglaladakota", "oglalalakota", linear_model_data_broiler$county)
linear_model_data_broiler$animal_density <- linear_model_data_broiler$BRL2022NUM.x / linear_model_data_broiler$Area..mi.2.
linear_model_data_broiler$surrounding_animal_density <- linear_model_data_broiler$broiler_count_summed / linear_model_data_broiler$area_summed
linear_model_data_broiler$surrounding_farm_density <- linear_model_data_broiler$hog_farms_summed / linear_model_data_broiler$area_summed
linear_model_data_broiler$farm_density <- linear_model_data_broiler$BRL2022FAC.x / linear_model_data_broiler$Area..mi.2.

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  county_temperature,
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTYNAME')
)

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               
county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  county_income,
  by.x = c('state', 'county'),
  by.y = c('State', 'County')
)    

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  cdl_named_df,
  by.x = c('state', 'county'),
  by.y = c('state', 'county')
  , all = TRUE
)

linear_model_data_broiler <- linear_model_data_broiler[complete.cases(linear_model_data_broiler), ]


# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_broiler[[col]] <- linear_model_data_broiler[[col]] * 0.000247105 * 100 / (linear_model_data_broiler$Area..mi.2. * 640)
}


linear_model_data_broiler = dplyr::select(linear_model_data_broiler, 
                                       "state", 
                                       "county", 
                                       "pop_summed", 
                                       "area_summed",
                                       "broiler_farms_summed",
                                       "broiler_count_summed",
                                       "Population..2020.census.",
                                       "Area..mi.2.",
                                       "BRL2022FAC.x",
                                       "BRL2022NUM.x",
                                       "BRL2022FAC.y",
                                       "BRL2022NUM.y",
                                       "surrounding_population_density", 
                                       "population_density",
                                       "animal_density",
                                       "farm_density",
                                       "surrounding_animal_density",
                                       "surrounding_farm_density",
                                       "Cooling.Degree.Days_JAN", 
                                       "Heating.Degree.Days_JAN", 
                                       "pcp_JAN", 
                                       "tavg_JAN", 
                                       "tmax_JAN", 
                                       "tmin_JAN", 
                                       "Cooling.Degree.Days_FEB", 
                                       "Heating.Degree.Days_FEB", 
                                       "pcp_FEB", 
                                       "tavg_FEB", 
                                       "tmax_FEB", 
                                       "tmin_FEB", 
                                       "Cooling.Degree.Days_MAR", 
                                       "Heating.Degree.Days_MAR", 
                                       "pcp_MAR", 
                                       "tavg_MAR", 
                                       "tmax_MAR", 
                                       "tmin_MAR",
                                       "Cooling.Degree.Days_APR",       
                                       "Heating.Degree.Days_APR", 
                                       "pcp_APR", 
                                       "tavg_APR", 
                                       "tmax_APR", 
                                       "tmin_APR",
                                       "Cooling.Degree.Days_MAY", 
                                       "Heating.Degree.Days_MAY", 
                                       "pcp_MAY", 
                                       "tavg_MAY", 
                                       "tmax_MAY", 
                                       "tmin_MAY", 
                                       "Cooling.Degree.Days_JUN", 
                                       "Heating.Degree.Days_JUN", 
                                       "pcp_JUN", 
                                       "tavg_JUN",                       
                                       "tmax_JUN",
                                       "tmin_JUN",
                                       "Cooling.Degree.Days_JUL", 
                                       "Heating.Degree.Days_JUL", 
                                       "pcp_JUL", 
                                       "tavg_JUL", 
                                       "tmax_JUL", 
                                       "tmin_JUL", 
                                       "Cooling.Degree.Days_AUG", 
                                       "Heating.Degree.Days_AUG", 
                                       "pcp_AUG", 
                                       "tavg_AUG", 
                                       "tmax_AUG", 
                                       "tmin_AUG",
                                       "Cooling.Degree.Days_SEP", 
                                       "Heating.Degree.Days_SEP", 
                                       "pcp_SEP", 
                                       "tavg_SEP", 
                                       "tmax_SEP", 
                                       "tmin_SEP",
                                       "Cooling.Degree.Days_OCT", 
                                       "Heating.Degree.Days_OCT", 
                                       "pcp_OCT", 
                                       "tavg_OCT", 
                                       "tmax_OCT", 
                                       "tmin_OCT",
                                       "Cooling.Degree.Days_NOV", 
                                       "Heating.Degree.Days_NOV", 
                                       "pcp_NOV", 
                                       "tavg_NOV", 
                                       "tmax_NOV", 
                                       "tmin_NOV",
                                       "Cooling.Degree.Days_DEC", 
                                       "Heating.Degree.Days_DEC", 
                                       "pcp_DEC", 
                                       "tavg_DEC", 
                                       "tmax_DEC", 
                                       "tmin_DEC",
                                       "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')
colnames(linear_model_data_broiler) = c( "State", 
                                      "County", 
                                      "surroundingPopulationSummed", 
                                      "surroundingAreaSummed",
                                      "surroundingBroilerFarmsSummed",
                                      "surroundingBroilerCountSummed",
                                      "Population..2020.census.",
                                      "Area..mi.2.",
                                      "broilerFarms",
                                      "broilerCount",
                                      "stateBroilerFarms",
                                      "stateBroilerCount",
                                      "surroundingPopulationDensity", 
                                      "populationDensity",
                                      "animalDensity",
                                      "farmDensity",
                                      "surroundAnimalDensity",
                                      "surroundingFarmDensity",
                                      "Cooling.Degree.Days_JAN", 
                                      "Heating.Degree.Days_JAN", 
                                      "pcp_JAN", 
                                      "tavg_JAN", 
                                      "tmax_JAN", 
                                      "tmin_JAN", 
                                      "Cooling.Degree.Days_FEB", 
                                      "Heating.Degree.Days_FEB", 
                                      "pcp_FEB", 
                                      "tavg_FEB", 
                                      "tmax_FEB", 
                                      "tmin_FEB", 
                                      "Cooling.Degree.Days_MAR", 
                                      "Heating.Degree.Days_MAR", 
                                      "pcp_MAR", 
                                      "tavg_MAR", 
                                      "tmax_MAR", 
                                      "tmin_MAR",
                                      "Cooling.Degree.Days_APR",       
                                      "Heating.Degree.Days_APR", 
                                      "pcp_APR", 
                                      "tavg_APR", 
                                      "tmax_APR", 
                                      "tmin_APR",
                                      "Cooling.Degree.Days_MAY", 
                                      "Heating.Degree.Days_MAY", 
                                      "pcp_MAY", 
                                      "tavg_MAY", 
                                      "tmax_MAY", 
                                      "tmin_MAY", 
                                      "Cooling.Degree.Days_JUN", 
                                      "Heating.Degree.Days_JUN", 
                                      "pcp_JUN", 
                                      "tavg_JUN",                       
                                      "tmax_JUN",
                                      "tmin_JUN",
                                      "Cooling.Degree.Days_JUL", 
                                      "Heating.Degree.Days_JUL", 
                                      "pcp_JUL", 
                                      "tavg_JUL", 
                                      "tmax_JUL", 
                                      "tmin_JUL", 
                                      "Cooling.Degree.Days_AUG", 
                                      "Heating.Degree.Days_AUG", 
                                      "pcp_AUG", 
                                      "tavg_AUG", 
                                      "tmax_AUG", 
                                      "tmin_AUG",
                                      "Cooling.Degree.Days_SEP", 
                                      "Heating.Degree.Days_SEP", 
                                      "pcp_SEP", 
                                      "tavg_SEP", 
                                      "tmax_SEP", 
                                      "tmin_SEP",
                                      "Cooling.Degree.Days_OCT", 
                                      "Heating.Degree.Days_OCT", 
                                      "pcp_OCT", 
                                      "tavg_OCT", 
                                      "tmax_OCT", 
                                      "tmin_OCT",
                                      "Cooling.Degree.Days_NOV", 
                                      "Heating.Degree.Days_NOV", 
                                      "pcp_NOV", 
                                      "tavg_NOV", 
                                      "tmax_NOV", 
                                      "tmin_NOV",
                                      "Cooling.Degree.Days_DEC", 
                                      "Heating.Degree.Days_DEC", 
                                      "pcp_DEC", 
                                      "tavg_DEC", 
                                      "tmax_DEC", 
                                      "tmin_DEC",
                                      "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')

write.csv(linear_model_data_broiler, "../Data/Animal Linear Model Data/linear_model_data_broiler_cafo.csv", row.names = FALSE)


head(linear_model_data_broiler, 10)
```
```{r}
layer_neighboring_count = neighboring_count

layer_neighboring_count_summed <- layer_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(Population..2020.census.),
            area_summed = sum(Area..mi.2.),
            cattle_farms_summed = sum(COW2022FAC),
            cattle_count_summed = sum(COW2022NUM),
            dairy_farms_summed = sum(DRY2022FAC),
            dairy_count_summed = sum(DRY2022NUM),
            broiler_farms_summed = sum(BRL2022FAC),
            broiler_count_summed = sum(BRL2022NUM),
            layer_farms_summed = sum(LAY2022FAC),
            layer_count_summed = sum(LAY2022NUM),
            hog_farms_summed = sum(HOG2022FAC),
            hog_count_summed = sum(HOG2022NUM)
  )

linear_model_data_layer = merge(
  layer_neighboring_count_summed,
  usda_w_pop_and_area_cleaned, 
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTY'),
  all = TRUE  
)

linear_model_data_layer = merge(
  linear_model_data_layer,
  state_subset,
  by.x = c('state'),
  by.y = c('STATE')
)

linear_model_data_layer$surrounding_population_density = linear_model_data_layer$pop_summed / linear_model_data_layer$area_summed
linear_model_data_layer$population_density = linear_model_data_layer$Population..2020.census. / linear_model_data_layer$Area..mi.2.
linear_model_data_layer$county <- gsub("oglaladakota", "oglalalakota", linear_model_data_layer$county)
linear_model_data_layer$animal_density <- linear_model_data_layer$LAY2022NUM.x / linear_model_data_layer$Area..mi.2.
linear_model_data_layer$surrounding_animal_density <- linear_model_data_layer$layer_count_summed / linear_model_data_layer$area_summed
linear_model_data_layer$surrounding_farm_density <- linear_model_data_layer$hog_farms_summed / linear_model_data_layer$area_summed
linear_model_data_layer$farm_density <- linear_model_data_layer$LAY2022FAC.x / linear_model_data_layer$Area..mi.2.

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_layer = merge(
  linear_model_data_layer,
  county_temperature,
  by.x = c('state', 'county'),
  by.y = c('STATE', 'COUNTYNAME')
)

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               
county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))

linear_model_data_layer = merge(
  linear_model_data_layer,
  county_income,
  by.x = c('state', 'county'),
  by.y = c('State', 'County')
)    

linear_model_data_layer = merge(
  linear_model_data_layer,
  cdl_named_df,
  by.x = c('state', 'county'),
  by.y = c('state', 'county')
  , all = TRUE
)

linear_model_data_layer <- linear_model_data_layer[complete.cases(linear_model_data_layer), ]


# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_layer[[col]] <- linear_model_data_layer[[col]] * 0.000247105 * 100 / (linear_model_data_layer$Area..mi.2. * 640)
}


linear_model_data_layer = dplyr::select(linear_model_data_layer, 
                                       "state", 
                                       "county", 
                                       "pop_summed", 
                                       "area_summed",
                                       "layer_farms_summed",
                                       "layer_count_summed",
                                       "Population..2020.census.",
                                       "Area..mi.2.",
                                       "LAY2022FAC.x",
                                       "LAY2022NUM.x",
                                       "LAY2022FAC.y",
                                       "LAY2022NUM.y",
                                       "surrounding_population_density", 
                                       "population_density",
                                       "animal_density",
                                       "farm_density",
                                       "surrounding_animal_density",
                                       "surrounding_farm_density",
                                       "Cooling.Degree.Days_JAN", 
                                       "Heating.Degree.Days_JAN", 
                                       "pcp_JAN", 
                                       "tavg_JAN", 
                                       "tmax_JAN", 
                                       "tmin_JAN", 
                                       "Cooling.Degree.Days_FEB", 
                                       "Heating.Degree.Days_FEB", 
                                       "pcp_FEB", 
                                       "tavg_FEB", 
                                       "tmax_FEB", 
                                       "tmin_FEB", 
                                       "Cooling.Degree.Days_MAR", 
                                       "Heating.Degree.Days_MAR", 
                                       "pcp_MAR", 
                                       "tavg_MAR", 
                                       "tmax_MAR", 
                                       "tmin_MAR",
                                       "Cooling.Degree.Days_APR",       
                                       "Heating.Degree.Days_APR", 
                                       "pcp_APR", 
                                       "tavg_APR", 
                                       "tmax_APR", 
                                       "tmin_APR",
                                       "Cooling.Degree.Days_MAY", 
                                       "Heating.Degree.Days_MAY", 
                                       "pcp_MAY", 
                                       "tavg_MAY", 
                                       "tmax_MAY", 
                                       "tmin_MAY", 
                                       "Cooling.Degree.Days_JUN", 
                                       "Heating.Degree.Days_JUN", 
                                       "pcp_JUN", 
                                       "tavg_JUN",                       
                                       "tmax_JUN",
                                       "tmin_JUN",
                                       "Cooling.Degree.Days_JUL", 
                                       "Heating.Degree.Days_JUL", 
                                       "pcp_JUL", 
                                       "tavg_JUL", 
                                       "tmax_JUL", 
                                       "tmin_JUL", 
                                       "Cooling.Degree.Days_AUG", 
                                       "Heating.Degree.Days_AUG", 
                                       "pcp_AUG", 
                                       "tavg_AUG", 
                                       "tmax_AUG", 
                                       "tmin_AUG",
                                       "Cooling.Degree.Days_SEP", 
                                       "Heating.Degree.Days_SEP", 
                                       "pcp_SEP", 
                                       "tavg_SEP", 
                                       "tmax_SEP", 
                                       "tmin_SEP",
                                       "Cooling.Degree.Days_OCT", 
                                       "Heating.Degree.Days_OCT", 
                                       "pcp_OCT", 
                                       "tavg_OCT", 
                                       "tmax_OCT", 
                                       "tmin_OCT",
                                       "Cooling.Degree.Days_NOV", 
                                       "Heating.Degree.Days_NOV", 
                                       "pcp_NOV", 
                                       "tavg_NOV", 
                                       "tmax_NOV", 
                                       "tmin_NOV",
                                       "Cooling.Degree.Days_DEC", 
                                       "Heating.Degree.Days_DEC", 
                                       "pcp_DEC", 
                                       "tavg_DEC", 
                                       "tmax_DEC", 
                                       "tmin_DEC",
                                       "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')
colnames(linear_model_data_layer) = c( "State", 
                                      "County", 
                                      "surroundingPopulationSummed", 
                                      "surroundingAreaSummed",
                                      "surroundingLayerFarmsSummed",
                                      "surroundingLayerCountSummed",
                                      "Population..2020.census.",
                                      "Area..mi.2.",
                                      "layerFarms",
                                      "layerCount",
                                      "stateLayerFarms",
                                      "stateLayerCount",
                                      "surroundingPopulationDensity", 
                                      "populationDensity",
                                      "animalDensity",
                                      "farmDensity",
                                      "surroundAnimalDensity",
                                      "surroundingFarmDensity",
                                      "Cooling.Degree.Days_JAN", 
                                      "Heating.Degree.Days_JAN", 
                                      "pcp_JAN", 
                                      "tavg_JAN", 
                                      "tmax_JAN", 
                                      "tmin_JAN", 
                                      "Cooling.Degree.Days_FEB", 
                                      "Heating.Degree.Days_FEB", 
                                      "pcp_FEB", 
                                      "tavg_FEB", 
                                      "tmax_FEB", 
                                      "tmin_FEB", 
                                      "Cooling.Degree.Days_MAR", 
                                      "Heating.Degree.Days_MAR", 
                                      "pcp_MAR", 
                                      "tavg_MAR", 
                                      "tmax_MAR", 
                                      "tmin_MAR",
                                      "Cooling.Degree.Days_APR",       
                                      "Heating.Degree.Days_APR", 
                                      "pcp_APR", 
                                      "tavg_APR", 
                                      "tmax_APR", 
                                      "tmin_APR",
                                      "Cooling.Degree.Days_MAY", 
                                      "Heating.Degree.Days_MAY", 
                                      "pcp_MAY", 
                                      "tavg_MAY", 
                                      "tmax_MAY", 
                                      "tmin_MAY", 
                                      "Cooling.Degree.Days_JUN", 
                                      "Heating.Degree.Days_JUN", 
                                      "pcp_JUN", 
                                      "tavg_JUN",                       
                                      "tmax_JUN",
                                      "tmin_JUN",
                                      "Cooling.Degree.Days_JUL", 
                                      "Heating.Degree.Days_JUL", 
                                      "pcp_JUL", 
                                      "tavg_JUL", 
                                      "tmax_JUL", 
                                      "tmin_JUL", 
                                      "Cooling.Degree.Days_AUG", 
                                      "Heating.Degree.Days_AUG", 
                                      "pcp_AUG", 
                                      "tavg_AUG", 
                                      "tmax_AUG", 
                                      "tmin_AUG",
                                      "Cooling.Degree.Days_SEP", 
                                      "Heating.Degree.Days_SEP", 
                                      "pcp_SEP", 
                                      "tavg_SEP", 
                                      "tmax_SEP", 
                                      "tmin_SEP",
                                      "Cooling.Degree.Days_OCT", 
                                      "Heating.Degree.Days_OCT", 
                                      "pcp_OCT", 
                                      "tavg_OCT", 
                                      "tmax_OCT", 
                                      "tmin_OCT",
                                      "Cooling.Degree.Days_NOV", 
                                      "Heating.Degree.Days_NOV", 
                                      "pcp_NOV", 
                                      "tavg_NOV", 
                                      "tmax_NOV", 
                                      "tmin_NOV",
                                      "Cooling.Degree.Days_DEC", 
                                      "Heating.Degree.Days_DEC", 
                                      "pcp_DEC", 
                                      "tavg_DEC", 
                                      "tmax_DEC", 
                                      "tmin_DEC",
                                      "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction",
                                        'total_crop',
                                        'total_crop_fraction',
                                        'state_total_crop',
                                        'state_total_alfalfa',
                                        'state_total_corn',
                                        'state_total_soy',
                                        'state_total_fraction')

write.csv(linear_model_data_layer, "../Data/Animal Linear Model Data/linear_model_data_layer_cafo.csv", row.names = FALSE)


head(linear_model_data_layer, 10)
```