---
title: "Untitled"
output: html_document
date: "2024-05-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(data.table)
library(sets)
library(stringr)
library(tidyr)
library(stargazer)
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
```


```{r}
usda_data = read.csv("../Data/usda_data.csv")
head(usda_data, 10)
neighbor_county_updated = read.csv("../Data/neighbor_county_updated.csv")
neighbor_county_updated <- neighbor_county_updated[
  !(neighbor_county_updated$county == neighbor_county_updated$neighboring_county & 
    neighbor_county_updated$state == neighbor_county_updated$neighboring_state), ]
head(neighbor_county_updated, 10)

values_to_filter <- c(2527, 1470, 2128, 973, 2431, 3022, 867, 767, 2039, 85, 2243, 1, 298, 2827, 1642, 1299, 1884, 674, 366, 1387, 571, 220, 161, 2206, 2364, 1094, 1215, 2966, 1821, 1585, 2926, 526, 1787, 2782, 1985, 2317, 69, 3095, 1176, 2812, 1159, 1736, 1200, 1765, 285, 1754, 294, 2311)

state_subset <- usda_data[usda_data$X %in% values_to_filter, ]
state_subset$state <- tolower(state_subset$state)
state_subset$state <- gsub("_", " ", state_subset$state)
```


```{r}

usda_w_pop_and_area = read.csv("../Data/usda_w_pop_and_area.csv")
head(usda_w_pop_and_area, 10)

neighbor_county_filtered <- neighbor_county_updated[!(neighbor_county_updated$state == neighbor_county_updated$neighboring_state & neighbor_county_updated$county == neighbor_county_updated$neighboring_county), ]

usda_w_pop_and_area_simplified = dplyr::select(usda_w_pop_and_area, "region", "subregion", "Population..2020.census.", "Area..mi.2.")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]
neighbor_county_updated <- subset(neighbor_county_updated, county != "buenavistacity")
neighbor_county_updated <- subset(neighbor_county_updated, neighboring_county != "buenavistacity")


neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)
neighboring_count_summed <- neighboring_count %>%
  group_by(state, county) %>%
  summarise(
    pop_summed = sum(Population..2020.census., na.rm = TRUE),
    area_summed = sum(Area..mi.2., na.rm = TRUE)
  )


```

```{r}
usda_w_pop_and_area_simplified = dplyr::select(usda_w_pop_and_area, "region", 
                                        "subregion", 
                                        "Population..2020.census.", 
                                        "Area..mi.2.",
                                        "cattle.farms",
                                        "cattle.count",
                                        "hog.farm",
                                        "hog.count",
                                        "sheep.farm",
                                        "sheep.count",
                                        "broiler.farm",
                                        "broiler.count",
                                        "layer.farm",
                                        "layer.count")
usda_w_pop_and_area_simplified = usda_w_pop_and_area_simplified[!duplicated(usda_w_pop_and_area_simplified), ]
usda_w_pop_and_area_simplified[is.na(usda_w_pop_and_area_simplified)] <- 0

neighboring_count =  merge(
  neighbor_county_updated,
  usda_w_pop_and_area_simplified, 
  by.x = c('neighboring_state', 'neighboring_county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

neighboring_count$sheep.count <- as.integer(gsub(-47, 0, neighboring_count$sheep.count))
neighboring_count$hog.count <- as.integer(gsub(-47, 0, neighboring_count$hog.count))
neighboring_count$cattle.count <- as.integer(gsub(-47, 0, neighboring_count$cattle.count))
neighboring_count$layer.count <- as.integer(gsub(-47, 0, neighboring_count$layer.count))
neighboring_count$broiler.count <- as.integer(gsub(-47, 0, neighboring_count$broiler.count))

neighboring_count$sheep.count[is.na(neighboring_count$sheep.count)] <- 0
neighboring_count$hog.count[is.na(neighboring_count$hog.count)] <- 0
neighboring_count$cattle.count[is.na(neighboring_count$cattle.count)] <- 0
neighboring_count$layer.count[is.na(neighboring_count$layer.count)] <- 0
neighboring_count$broiler.count[is.na(neighboring_count$broiler.count)] <- 0

neighboring_count$sheep.farm[is.na(neighboring_count$sheep.farm)] <- 0
neighboring_count$hog.farm[is.na(neighboring_count$hog.farm)] <- 0
neighboring_count$cattle.farms[is.na(neighboring_count$cattle.farms)] <- 0
neighboring_count$layer.farm[is.na(neighboring_count$layer.farm)] <- 0
neighboring_count$broiler.farm[is.na(neighboring_count$broiler.farm)] <- 0
values_to_filter <- c(2029, 10868, 11374)

neighboring_count <- neighboring_count[-values_to_filter, ]

```

```{r}
# Load built-in FIPS reference from tidycensus
data("fips_codes")

# Load CDL crop raster summary (county-lvel pixel counts)
cdl_df <- read.csv(file = "../Data/county_pixel_count_2024_10.csv") %>% 
  rename(fips = Fips) %>%
  mutate(fips = sprintf("%05d", as.integer(fips)))

# Build FIPS lookup table (state and county names)
fips_lookup <- fips_codes %>%
  mutate(fips = paste0(state_code, county_code)) %>%
  dplyr::select(fips, state = state_name, county) %>%
  mutate(
    state = tolower(state),
    county = tolower(gsub("county", "", county)),
    county = gsub("[[:space:][:punct:]]", "", county)
  )


# Merge CDL pixel counts with cleaned state and county names
cdl_named_df <- cdl_df %>%
  left_join(fips_lookup, by = "fips")

cdl_named_df$county <- gsub("county", "", cdl_named_df$county) 
cdl_named_df$county <- gsub("parish", "", cdl_named_df$county) 
cdl_named_df$county <- gsub("miamidade", "miami-dade", cdl_named_df$county) 
cdl_named_df$county <- ifelse(
  cdl_named_df$state == "virginia" &
    !tolower(cdl_named_df$county) %in% c("jamescity", "charlescity"),
  gsub("city", "", cdl_named_df$county, ignore.case = TRUE),
  cdl_named_df$county
)


cdl_named_df <- dplyr::select(cdl_named_df,
                              state,
                              county,
                              Category_001,
                              Category_005,
                              Category_036)

colnames(cdl_named_df) = c('state',
                           'county',
                           'corn_fraction',
                           'soy_fraction',
                           "alfalfa_fraction")
```



```{r}
sheep_neighboring_count = neighboring_count

sheep_neighboring_count_summed <- sheep_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )


linear_model_data_sheep = merge(
  sheep_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_sheep = merge(
  linear_model_data_sheep,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_sheep$surrounding_population_density = linear_model_data_sheep$pop_summed / linear_model_data_sheep$area_summed
linear_model_data_sheep$population_density = linear_model_data_sheep$Population..2020.census. / linear_model_data_sheep$Area..mi.2.
linear_model_data_sheep$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_sheep$county.x)
linear_model_data_sheep$animal_density <- linear_model_data_sheep$sheep.count.x / linear_model_data_sheep$Area..mi.2.
linear_model_data_sheep$surrounding_animal_density <- linear_model_data_sheep$sheep.count.x / linear_model_data_sheep$Area..mi.2.
linear_model_data_sheep$surrounding_farm_density <- linear_model_data_sheep$sheep_farms_summed / linear_model_data_sheep$area_summed
linear_model_data_sheep$farm_density <- linear_model_data_sheep$sheep.farm.x / linear_model_data_sheep$Area..mi.2.

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_sheep = merge(
  linear_model_data_sheep,
  county_temperature,
  by.x = c('state', 'county.x'),
  by.y = c('STATE', 'COUNTYNAME')
  )

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               

county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))
                                                                                                                               
linear_model_data_sheep = merge(
  linear_model_data_sheep,
  county_income,
  by.x = c('state', 'county.x'),
  by.y = c('State', 'County')
  , all = TRUE
  )   

linear_model_data_sheep = merge(
  linear_model_data_sheep,
  cdl_named_df,
  by.x = c('state', 'county.x'),
  by.y = c('state', 'county')
  , all = TRUE
  )

# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_sheep[[col]] <- linear_model_data_sheep[[col]] * 0.000247105 * 100 / (linear_model_data_sheep$Area..mi.2. * 640)
}


linear_model_data_sheep = dplyr::select(linear_model_data_sheep, 
                                        "state", 
                                        "county.x", 
                                        "pop_summed", 
                                        "area_summed",
                                        "sheep_farms_summed",
                                        "sheep_count_summed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "sheep.farm.x",
                                        "sheep.count.x",
                                        "sheep.farm.y",
                                        "sheep.count.y",
                                        "surrounding_population_density", 
                                        "population_density",
                                        "animal_density",
                                        "farm_density",
                                        "surrounding_animal_density",
                                        "surrounding_farm_density",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")
colnames(linear_model_data_sheep) = c(  "State", 
                                        "County", 
                                        "surroundingPopulationSummed", 
                                        "surroundingAreaSummed",
                                        "surroundingSheepFarmsSummed",
                                        "surroundingSheepCountSummed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "sheepFarms",
                                        "sheepCount",
                                        "stateSheepFarms",
                                        "stateSheepCount",
                                        "surroundingPopulationDensity", 
                                        "populationDensity",
                                        "animalDensity",
                                        "farmDensity",
                                        "surroundAnimalDensity",
                                        "surroundingFarmDensity",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "personalIncome2022",
                                        'corn_fraction',
                                        'soy_fraction',
                                        "alfalfa_fraction")
                                                                                                                               
write.csv(linear_model_data_sheep, "../Data/Animal Linear Model Data/linear_model_data_sheep.csv", row.names = FALSE)

# county_income_data = https://www.bea.gov/data/income-saving/personal-income-county-metro-and-other-areas
# county_weather_data


head(linear_model_data_sheep)
```


```{r}
cattle_neighboring_count = neighboring_count

cattle_neighboring_count_summed <- cattle_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattle_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_cattle = merge(
  cattle_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_cattle = merge(
  linear_model_data_cattle,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_cattle$surrounding_population_density = linear_model_data_cattle$pop_summed / linear_model_data_cattle$area_summed
linear_model_data_cattle$population_density = linear_model_data_cattle$Population..2020.census. / linear_model_data_cattle$Area..mi.2.
linear_model_data_cattle$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_cattle$county.x)
linear_model_data_cattle$animal_density <- linear_model_data_cattle$cattle.count.x / linear_model_data_cattle$Area..mi.2.
linear_model_data_cattle$surrounding_animal_density <- linear_model_data_cattle$cattle_count_summed / linear_model_data_cattle$area_summed

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_cattle = merge(
  linear_model_data_cattle,
  county_temperature,
  by.x = c('state', 'county.x'),
  by.y = c('STATE', 'COUNTYNAME')
  )

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               
county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))
                                 
linear_model_data_cattle = merge(
  linear_model_data_cattle,
  county_income,
  by.x = c('state', 'county.x'),
  by.y = c('State', 'County')
  )    

linear_model_data_cattle = merge(
  linear_model_data_cattle,
  cdl_named_df,
  by.x = c('state', 'county.x'),
  by.y = c('state', 'county')
  , all = TRUE
  )

# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_cattle[[col]] <- linear_model_data_cattle[[col]] * 0.000247105 * 100 / (linear_model_data_cattle$Area..mi.2. * 640)
}


linear_model_data_cattle = dplyr::select(linear_model_data_cattle, 
                                        "state", 
                                        "county.x", 
                                        "pop_summed", 
                                        "area_summed",
                                        "cattle_farms_summed",
                                        "cattle_count_summed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "cattle.farms.x",
                                        "cattle.count.x",
                                        "cattle.farms.y",
                                        "cattle.count.y",
                                        "surrounding_population_density", 
                                        "population_density",
                                        "animal_density",
                                        "surrounding_animal_density",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")
colnames(linear_model_data_cattle) = c(  "State", 
                                        "County", 
                                        "surroundingPopulationSummed", 
                                        "surroundingAreaSummed",
                                        "surroundingCattleFarmsSummed",
                                        "surroundingCattleCountSummed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "cattleFarms",
                                        "cattleCount",
                                        "stateCattleFarms",
                                        "stateCattleCount",
                                        "surroundingPopulationDensity", 
                                        "populationDensity",
                                        "animalDensity",
                                        "surroundAnimalDensity",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")

write.csv(linear_model_data_cattle, "../Data/Animal Linear Model Data/linear_model_data_cattle.csv", row.names = FALSE)


head(linear_model_data_cattle, 10)
```

```{r}
broiler_neighboring_count = neighboring_count

broiler_neighboring_count_summed <- broiler_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_broiler = merge(
  broiler_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_broiler$surrounding_population_density = linear_model_data_broiler$pop_summed / linear_model_data_broiler$area_summed
linear_model_data_broiler$population_density = linear_model_data_broiler$Population..2020.census. / linear_model_data_broiler$Area..mi.2.
linear_model_data_broiler$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_broiler$county.x)
linear_model_data_broiler$animal_density <- linear_model_data_broiler$broiler.count.x / linear_model_data_broiler$Area..mi.2.
linear_model_data_broiler$surrounding_animal_density <- linear_model_data_broiler$broiler_count_summed / linear_model_data_broiler$area_summed
linear_model_data_broiler$surrounding_farm_density <- linear_model_data_broiler$broiler_farms_summed / linear_model_data_broiler$area_summed
linear_model_data_broiler$farm_density <- linear_model_data_broiler$broiler.count.x / linear_model_data_broiler$Area..mi.2.

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  county_temperature,
  by.x = c('state', 'county.x'),
  by.y = c('STATE', 'COUNTYNAME')
  )

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               

county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))
                                 
linear_model_data_broiler = merge(
  linear_model_data_broiler,
  county_income,
  by.x = c('state', 'county.x'),
  by.y = c('State', 'County')
  )    

linear_model_data_broiler = merge(
  linear_model_data_broiler,
  cdl_named_df,
  by.x = c('state', 'county.x'),
  by.y = c('state', 'county')
  , all = TRUE
  )

# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_broiler[[col]] <- linear_model_data_broiler[[col]] * 0.000247105 * 100 / (linear_model_data_broiler$Area..mi.2. * 640)
}

linear_model_data_broiler = dplyr::select(linear_model_data_broiler, 
                                        "state", 
                                        "county.x", 
                                        "pop_summed", 
                                        "area_summed",
                                        "broiler_farms_summed",
                                        "broiler_count_summed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "broiler.farm.x",
                                        "broiler.count.x",
                                        "broiler.farm.y",
                                        "broiler.count.y",
                                        "surrounding_population_density", 
                                        "population_density",
                                        "animal_density",
                                        "farm_density",
                                        "surrounding_animal_density",
                                        "surrounding_farm_density",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")
colnames(linear_model_data_broiler) = c(  "State", 
                                        "County", 
                                        "surroundingPopulationSummed", 
                                        "surroundingAreaSummed",
                                        "surroundingBroilerFarmsSummed",
                                        "surroundingBroilerCountSummed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "broilerFarms",
                                        "broilerCount",
                                        "stateBroilerFarms",
                                        "stateBroilerCount",
                                        "surroundingPopulationDensity", 
                                        "populationDensity",
                                        "animalDensity",
                                        "farmDensity",
                                        "surroundAnimalDensity",
                                        "surroundingFarmDensity",                                        
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")

write.csv(linear_model_data_broiler, "../Data/Animal Linear Model Data/linear_model_data_broiler.csv", row.names = FALSE)



head(linear_model_data_broiler, 10)
```

```{r}
layer_neighboring_count = neighboring_count

layer_neighboring_count_summed <- layer_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_layer = merge(
  layer_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_layer = merge(
  linear_model_data_layer,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_layer$surrounding_population_density = linear_model_data_layer$pop_summed / linear_model_data_layer$area_summed
linear_model_data_layer$population_density = linear_model_data_layer$Population..2020.census. / linear_model_data_layer$Area..mi.2.
linear_model_data_layer$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_layer$county.x)
linear_model_data_layer$animal_density <- linear_model_data_layer$layer.count.x / linear_model_data_layer$Area..mi.2.
linear_model_data_layer$surrounding_animal_density <- linear_model_data_layer$layer_count_summed / linear_model_data_layer$area_summed
linear_model_data_layer$surrounding_farm_density <- linear_model_data_layer$layer_farms_summed / linear_model_data_layer$area_summed
linear_model_data_layer$farm_density <- linear_model_data_layer$layer.farm.x / linear_model_data_layer$Area..mi.2.



county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_layer = merge(
  linear_model_data_layer,
  county_temperature,
  by.x = c('state', 'county.x'),
  by.y = c('STATE', 'COUNTYNAME')
  )

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               

county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))
                                 
linear_model_data_layer = merge(
  linear_model_data_layer,
  county_income,
  by.x = c('state', 'county.x'),
  by.y = c('State', 'County')
  )    

linear_model_data_layer = merge(
  linear_model_data_layer,
  cdl_named_df,
  by.x = c('state', 'county.x'),
  by.y = c('state', 'county')
  , all = TRUE
  )

# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_layer[[col]] <- linear_model_data_layer[[col]] * 0.000247105 * 100 / (linear_model_data_layer$Area..mi.2. * 640)
}

linear_model_data_layer = dplyr::select(linear_model_data_layer, 
                                        "state", 
                                        "county.x", 
                                        "pop_summed", 
                                        "area_summed",
                                        "layer_farms_summed",
                                        "layer_count_summed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "layer.farm.x",
                                        "layer.count.x",
                                        "layer.farm.y",
                                        "layer.count.y",
                                        "surrounding_population_density", 
                                        "population_density",
                                        "animal_density",
                                        "farm_density",
                                        "surrounding_animal_density",
                                        "surrounding_farm_density",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")
colnames(linear_model_data_layer) = c(  "State", 
                                        "County", 
                                        "surroundingPopulationSummed", 
                                        "surroundingAreaSummed",
                                        "surroundingLayerFarmsSummed",
                                        "surroundingLayerCountSummed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "layerFarms",
                                        "layerCount",
                                        "stateLayerFarms",
                                        "stateLayerCount",
                                        "surroundingPopulationDensity", 
                                        "populationDensity",
                                        "animalDensity",
                                        "farmDensity",
                                        "surroundAnimalDensity",
                                        "surroundingFarmDensity",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")

write.csv(linear_model_data_layer, "../Data/Animal Linear Model Data/linear_model_data_layer.csv", row.names = FALSE)

head(linear_model_data_layer, 10)
```

```{r}
hog_neighboring_count = neighboring_count

hog_neighboring_count_summed <- hog_neighboring_count %>%
  group_by(state, county) %>%
  summarise(pop_summed = sum(`Population..2020.census.`),
            area_summed = sum(`Area..mi.2.`),
            cattled_farms_summed = sum(`cattle.farms`),
            cattle_count_summed = sum(cattle.count),
            broiler_farms_summed = sum(broiler.farm),
            broiler_count_summed = sum(broiler.count),
            layer_farms_summed = sum(layer.farm),
            layer_count_summed = sum(layer.count),
            hog_farms_summed = sum(hog.farm),
            hog_count_summed = sum(hog.count),
            sheep_farms_summed = sum(sheep.farm),
            sheep_count_summed = sum(sheep.count)
            )

linear_model_data_hog = merge(
  hog_neighboring_count_summed,
  usda_w_pop_and_area_simplified, 
  by.x = c('state', 'county'),
  by.y = c('region', 'subregion'),
  all = TRUE  
)

linear_model_data_hog = merge(
  linear_model_data_hog,
  state_subset,
  by.x = c('state'),
  by.y = c('state')
)

linear_model_data_hog$surrounding_population_density = linear_model_data_hog$pop_summed / linear_model_data_hog$area_summed
linear_model_data_hog$population_density = linear_model_data_hog$Population..2020.census. / linear_model_data_hog$Area..mi.2.
linear_model_data_hog$county.x <- gsub("oglaladakota", "oglalalakota", linear_model_data_hog$county.x)
linear_model_data_hog$animal_density <- linear_model_data_hog$hog.count.x / linear_model_data_hog$Area..mi.2.
linear_model_data_hog$surrounding_animal_density <- linear_model_data_hog$hog_count_summed / linear_model_data_hog$area_summed
linear_model_data_hog$surrounding_farm_density <- linear_model_data_hog$hog_farms_summed / linear_model_data_hog$area_summed
linear_model_data_hog$farm_density <- linear_model_data_hog$hog.farm.x / linear_model_data_hog$Area..mi.2.

county_temperature = read.csv("../Data/NOAA County Temperature Data 2013-2023.csv")

linear_model_data_hog = merge(
  linear_model_data_hog,
  county_temperature,
  by.x = c('state', 'county.x'),
  by.y = c('STATE', 'COUNTYNAME')
  )

county_income = read.csv("../Data/county_per_capita_income.csv")                                                                               

county_income$State <- tolower(county_income$State)    
county_income$County <- tolower(county_income$County)
county_income$County <- gsub(" ", "", county_income$County)  
county_income$County <- gsub("\\.", "", county_income$County)   
county_income$County <- gsub("'", "", county_income$County)   
county_income$X2022 <- gsub(",", "", county_income$X2022) 
county_income$County <- gsub("doñaana", "donaana", county_income$County)   
county_income = transform(county_income, X2022 = as.numeric(X2022))
                                                                                                                               
linear_model_data_hog = merge(
  linear_model_data_hog,
  county_income,
  by.x = c('state', 'county.x'),
  by.y = c('State', 'County')
  , all = TRUE
  )    

linear_model_data_hog = merge(
  linear_model_data_hog,
  cdl_named_df,
  by.x = c('state', 'county.x'),
  by.y = c('state', 'county')
  , all = TRUE
  )

# List of crop fraction columns to update
crop_cols <- c("corn_fraction", "soy_fraction", "alfalfa_fraction")

# Apply the formula to each crop column
for (col in crop_cols) {
  linear_model_data_hog[[col]] <- linear_model_data_hog[[col]] * 0.000247105 * 100 / (linear_model_data_hog$Area..mi.2. * 640)
}

linear_model_data_hog = dplyr::select(linear_model_data_hog, 
                                        "state", 
                                        "county.x", 
                                        "pop_summed", 
                                        "area_summed",
                                        "hog_farms_summed",
                                        "hog_count_summed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "hog.farm.x",
                                        "hog.count.x",
                                        "hog.farm.y",
                                        "hog.count.y",
                                        "surrounding_population_density", 
                                        "population_density",
                                        "animal_density",
                                        "farm_density",
                                        "surrounding_animal_density",
                                        "surrounding_farm_density",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "X2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")
colnames(linear_model_data_hog) = c(  "State", 
                                        "County", 
                                        "surroundingPopulationSummed", 
                                        "surroundingAreaSummed",
                                        "surroundingHogFarmsSummed",
                                        "surroundingHogCountSummed",
                                        "Population..2020.census.",
                                        "Area..mi.2.",
                                        "hogFarms",
                                        "hogCount",
                                        "stateHogFarms",
                                        "stateHogCount",
                                        "surroundingPopulationDensity", 
                                        "populationDensity",
                                        "animalDensity",
                                        "farmDensity",
                                        "surroundAnimalDensity",
                                        "surroundingFarmDensity",
                                        "Cooling.Degree.Days_JAN", 
                                        "Heating.Degree.Days_JAN", 
                                        "pcp_JAN", 
                                        "tavg_JAN", 
                                        "tmax_JAN", 
                                        "tmin_JAN", 
                                        "Cooling.Degree.Days_FEB", 
                                        "Heating.Degree.Days_FEB", 
                                        "pcp_FEB", 
                                        "tavg_FEB", 
                                        "tmax_FEB", 
                                        "tmin_FEB", 
                                        "Cooling.Degree.Days_MAR", 
                                        "Heating.Degree.Days_MAR", 
                                        "pcp_MAR", 
                                        "tavg_MAR", 
                                        "tmax_MAR", 
                                        "tmin_MAR",
                                        "Cooling.Degree.Days_APR",       
                                        "Heating.Degree.Days_APR", 
                                        "pcp_APR", 
                                        "tavg_APR", 
                                        "tmax_APR", 
                                        "tmin_APR",
                                        "Cooling.Degree.Days_MAY", 
                                        "Heating.Degree.Days_MAY", 
                                        "pcp_MAY", 
                                        "tavg_MAY", 
                                        "tmax_MAY", 
                                        "tmin_MAY", 
                                        "Cooling.Degree.Days_JUN", 
                                        "Heating.Degree.Days_JUN", 
                                        "pcp_JUN", 
                                        "tavg_JUN",                       
                                        "tmax_JUN",
                                        "tmin_JUN",
                                        "Cooling.Degree.Days_JUL", 
                                        "Heating.Degree.Days_JUL", 
                                        "pcp_JUL", 
                                        "tavg_JUL", 
                                        "tmax_JUL", 
                                        "tmin_JUL", 
                                        "Cooling.Degree.Days_AUG", 
                                        "Heating.Degree.Days_AUG", 
                                        "pcp_AUG", 
                                        "tavg_AUG", 
                                        "tmax_AUG", 
                                        "tmin_AUG",
                                        "Cooling.Degree.Days_SEP", 
                                        "Heating.Degree.Days_SEP", 
                                        "pcp_SEP", 
                                        "tavg_SEP", 
                                        "tmax_SEP", 
                                        "tmin_SEP",
                                        "Cooling.Degree.Days_OCT", 
                                        "Heating.Degree.Days_OCT", 
                                        "pcp_OCT", 
                                        "tavg_OCT", 
                                        "tmax_OCT", 
                                        "tmin_OCT",
                                        "Cooling.Degree.Days_NOV", 
                                        "Heating.Degree.Days_NOV", 
                                        "pcp_NOV", 
                                        "tavg_NOV", 
                                        "tmax_NOV", 
                                        "tmin_NOV",
                                        "Cooling.Degree.Days_DEC", 
                                        "Heating.Degree.Days_DEC", 
                                        "pcp_DEC", 
                                        "tavg_DEC", 
                                        "tmax_DEC", 
                                        "tmin_DEC",
                                        "personalIncome2022",
                                        "corn_fraction",
                                        "soy_fraction",
                                        "alfalfa_fraction")

head(linear_model_data_hog, 10)

write.csv(linear_model_data_hog, "../Data/Animal Linear Model Data/linear_model_data_hog.csv", row.names = FALSE)

```

